### ISSUE TITLE
Fix Workbench hitboxes

### ISSUE THREAD

**Issue by InfornoFire** [CookieCNetwork/Chipped#10]
The workbenches are 2 x 1 or 2 x 2. Minecraft does not natively support blocks that are bigger than 1 x 1 x 1 (trying to use VoxelShape will end up making the block have unwanted properties. For this it is best to use a "fake block" similarly generated by a bed, this method should be similar to other mods like Immersive's engineer's workbench

**Comment by InfornoFire** [comment]
Fixed next update

**Comment by spotishii** [comment]
First issue :)
