### ISSUE TITLE
Z-fighting on loom model

### ISSUE THREAD

**Issue by Synthestra** [CookieCNetwork/Chipped#101]
![Screenshot_13](https://user-images.githubusercontent.com/22637135/149084813-8718536c-8a2e-4c38-87d1-8f7402ca9ed2.png)
![Screenshot_14](https://user-images.githubusercontent.com/22637135/149084831-b268076f-ca71-4b14-ac0c-7088490cd035.png)
![Screenshot_18](https://user-images.githubusercontent.com/22637135/149085317-ea7efa55-4936-4d90-b41c-c71380ef178e.png)

**Comment by terrariumearth** [comment]
this is being fixed, already fixed for 1.18.2, all the bench models have been redone to remove mixeling and z-fighting!
