### ISSUE TITLE
crash in 1.16.5

### ISSUE THREAD

**Issue by bilgosk** [CookieCNetwork/Chipped#105]
ver 1.0.6.
[crash-2022-01-27_17.18.24-fml.txt](https://github.com/WillowWorks/Chipped/files/7951168/crash-2022-01-27_17.18.24-fml.txt)
1
I dont know what is happening

**Comment by InfornoFire** [comment]
https://www.curseforge.com/minecraft/mc-mods/chipped/files/3591185
Try updating to 1.2.1 first
Anyways the issue seems to be related to workbenches: Exception message: java.lang.IllegalArgumentException: Block{null} has property: model with invalidly named value: maın
