### ISSUE TITLE
Tesselation issue

### ISSUE THREAD

**Issue by ChopinFrederic07** [CookieCNetwork/Chipped#109]
Hey, so there's an issue with tessellation, it only appears to happen when I am in the chunk of an andesite block from chipped, I crash instantly when I enter the world. 

[crash-2022-03-15_15.32.28-client.txt](https://github.com/WillowWorks/Chipped/files/8257713/crash-2022-03-15_15.32.28-client.txt)

It seems to disappear when I delete every folder from the 'world' except the region and playerdata. I have a feeling it's because of the connected texture that the block has or it's interfering with my Nvidia driver settings, either way I would appreciate some help as to how to fix it.

**Comment by terrariumearth** [comment]
This is a known CTM issue! We cannot fix this.
