### ISSUE TITLE
Chipped version of redstone lamps don't work

### ISSUE THREAD

**Issue by mcdodge34** [CookieCNetwork/Chipped#110]
Minecraft Forge 1.18.1
Forge version 39.0.79
chipped-1.18.1-1.2.1-forge

Simple as the title, I tried using a vanilla lever, a block of redstone, a button, none of them make the chipped redstone lamps version turn on or off, they are always off, when I turn them back to vanilla redstone lamps they work fine, but none of the chipped versions seems to produce light like I expected, your lamps have awesome models, but if they were working that would be epic.

**Comment by terrariumearth** [comment]
We no longer support 1.18.1, but this is fixed in later versions.
