### ISSUE TITLE
[Feature request] Compatibility with Domum Ornamentum

### ISSUE THREAD

**Issue by totrider** [CookieCNetwork/Chipped#112]
Could we get Domum Ornamentum compatibility?

[https://github.com/ldtteam/Domum-Ornamentum/tree/version/latest/src/datagen/generated/domum_ornamentum/data/domum_ornamentum/tags/blocks&nbsp;](http:)
"Mod compatibility:

By default, a modder will need to add his blocks to the required material tags (see above), however most of these already extend from other tags, as such, it generally suffices to add the planks or logs to the vanilla tag for DO to pick them up."

**Comment by AlexNijjar** [comment]
We have no interest in adding mod compat for the foreseeable future.
