### ISSUE TITLE
Chipped vine 17 does not have a texture.

### ISSUE THREAD

**Issue by RageQuitAmy** [CookieCNetwork/Chipped#114]
chipped:vine_17 does not have a texture when placed. The mod version is 1.18.1 fabric, chipped-1.2. 

![2022-03-22_15 33 23](https://user-images.githubusercontent.com/73620990/159519786-96bfba3c-b5f6-4fbf-9a79-5b99e4b79264.png)

**Comment by BFLIgames1234** [comment]
also having this issue and it wont load my worlds because of it

**Comment by RageQuitAmy** [comment]
:( Hopefully it will get fixed soon.

**Comment by terrariumearth** [comment]
this is a known issue that will be fixed, though @BFLIgames1234 , it would not cause you to not load worlds.

**Comment by RageQuitAmy** [comment]
Thank you!

**Comment by jmdev91** [comment]
In case you need it, here's a list of the missing files (1.18.2-Fabric v1.2.1):

chipped:models/block/vines/vine_9/vine_9_4u.json
chipped:models/block/vines/vine_9/vine_9_3u.json
chipped:models/block/vines/vine_9/vine_9_2u_opposite.json
chipped:models/block/vines/vine_9/vine_9_2u.json
chipped:models/block/vines/vine_9/vine_9_1u.json
chipped:models/block/vines/vine_9/vine_9_1.json
chipped:models/block/vines/vine_9/vine_9_2.json
chipped:models/block/vines/vine_9/vine_9_3.json
chipped:models/block/vines/vine_9/vine_9_4.json
chipped:models/block/vines/vine_9/vine_9_u.json
chipped:models/block/vines/vine_9/vine_9_2_opposite.json
chipped:textures/block/mason_table.png
chipped:textures/block/mechanist_workbench.png
chipped:textures/block/glassblower.png
chipped:textures/block/carpenters_table.png
chipped:textures/block/loom_table.png
chipped:textures/block/botanist_workbench.png

There's also some reference to an apparently missing/nonexistant minecraft:textures/0.png mixed in with the other FileNotFoundExceptions, leading me to suspect it might be referenced by this mod.

**Comment by terrariumearth** [comment]
Fixed in next update with addition of all new texture revamp!
