### ISSUE TITLE
[Render thread/ERROR]: Couldn't parse loot table chipped:blocks/dried_kelp_block

### ISSUE THREAD

**Issue by StroII** [CookieCNetwork/Chipped#115]
I'm trying to use Chipped on Fabric but every time I try running the game... well, the game opens but if I try opening a map, the game dies. (I have other mods, though, so I'm sorry if it's a conflict with other mods that's causing the problem and not your own. I don't know anything about programming.)
Looking through the log, I get this error (but here's the [latest.log](https://github.com/Toadstool-Studios/Chipped/files/8346763/latest.log) if you want to look through the whole thing) for dried_kelp_block 1 through 12:

> [20:52:12] [Render thread/ERROR]: Couldn't parse loot table chipped:blocks/dried_kelp_block_1
> com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'chipped:dried_kelp_block_1'
> 	at net.minecraft.class_3518.method_17995(class_3518.java:130) ~[client-intermediary.jar:?]
> 	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
> 	at net.minecraft.class_3518.method_15256(class_3518.java:130) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3518.method_15288(class_3518.java:138) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_77$class_78.method_413(class_77.java:55) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_77$class_78.method_443(class_77.java:40) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_85$class_90.method_441(class_85.java:151) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[client-intermediary.jar:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
> 	at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3518.method_15272(class_3518.java:456) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[client-intermediary.jar:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
> 	at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_52$class_54.method_340(class_52.java:213) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_52$class_54.deserialize(class_52.java:209) ~[client-intermediary.jar:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.8.jar:?]
> 	at net.minecraft.class_60.method_20711(class_60.java:44) ~[client-intermediary.jar:?]
> 	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
> 	at net.minecraft.class_60.method_20712(class_60.java:42) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_60.method_18788(class_60.java:17) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
> 	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_29604(class_310.java:2154) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_29610(class_310.java:2003) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_29607(class_310.java:1947) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_525.method_2736(class_525.java:278) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_525.method_19922(class_525.java:214) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_4185.method_25306(class_4185.java:40) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_339.method_25402(class_339.java:121) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_437.method_25412(class_437.java:491) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1255.execute(class_1255.java:101) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
> 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
> 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
> 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
> 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:202) [client-intermediary.jar:?]
> 	at net.minecraft.class_1041.method_15998(class_1041.java:310) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_1523(class_310.java:1142) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]

**Comment by StroII** [comment]
I've discovered that one of the mods I used was actually a modpack containing many of the other mods I was using and, thus, it was probably the cause of this problem.

**Comment by KingofMidnight** [comment]
this is happening the same to me on the server I work on

**Comment by terrariumearth** [comment]
this is fixed in 1.18.2, ill see about fixing it for 1.18.1
