### ISSUE TITLE
update to 1.18.2

### ISSUE THREAD

**Issue by scyborne** [CookieCNetwork/Chipped#116]
hi when is this being updated to 1.18.2

**Comment by rostikmak** [comment]
Hello, sorry if I'm annoying, but can you tell at least approximately: when the mod will be released on 1.18.2.
I'm really looking forward to your mod on 1.18.2.
Translated by google translator.
He is wonderful.
Thanks a lot.
Have nice day! (this phrases written by me =) ).

**Comment by terrariumearth** [comment]
1.18.2 can be found here:
Forge: https://www.curseforge.com/minecraft/mc-mods/chipped/files/3745340
Fabric: https://www.curseforge.com/minecraft/mc-mods/chipped/files/3745343
