### ISSUE TITLE
Missing Texture - Connected Textures

### ISSUE THREAD

**Issue by Mdinaa** [CookieCNetwork/Chipped#117]
There seems to be an issue with the connecting of textures for the Dark Oak Plank - Chipped Variant, happens to quite a few of the dark oak textures, any idea on whether this can be fixed?

MC Version: 1.16.5
Chipped Version: 1.16.5 1.2.1 Tag Fix

![image](https://user-images.githubusercontent.com/97696972/160277226-6337e211-92c2-4fe6-a1e8-8d12c893bd5b.png)

**Comment by terrariumearth** [comment]
Fixed in next update with addition of all new textures
