### ISSUE TITLE
Can't join or create world with this mod.

### ISSUE THREAD

**Issue by Anonyma00** [CookieCNetwork/Chipped#118]
Everytime i try to join or make a world with this mod (Fabric, 1.18.2), minecraft tells me there's an error with a datapack i am using (Is a mod the same as a datapack or not? Because i am not using any datapacks if it's something different than a mod). Then Minecraft gives me the option to use safe mode or go back to the title screen and fix it myself. Safe mod doesn't work by the way. 
I tried to find a solution but couldn't. Can anyone help me with this?

Edit: Making a server with the mod (using Aternos) also makes the server crash when starting.

**Comment by amidnightblue** [comment]
Same problem here. Fabric, 1.18.2, never used Chipped before. Can't open any world at all if chipped-1.2.jar is in the mods folder. 

(As I was checking that I had the right version I realised I had misread and it's not updated to 1.18.2. Sorry! Is that in the works?)

**Comment by terrariumearth** [comment]
1.18.2 Fabric was just released:
Fabric: https://www.curseforge.com/minecraft/mc-mods/chipped/files/3745343
