### ISSUE TITLE
Add stonecutter-like recipes

### ISSUE THREAD

**Issue by artemisSystem** [CookieCNetwork/Chipped#119]
Currently it seems recipes are just a list of tags for each workstation. For modpack devs, it would be really cool if there was added a new recipe type that allows you to define recipes in the same format as the stonecutter (maybe allowing tags as results if this isn't supported already by mojang, not sure). This would allow you to use the workstations as more general recipe stations, to make a single item make multiple result items (like 1 plank -> 2 slabs) for example. It would also allow for adding recipes for a better JEI experience, by adding a <vanilla item> to <tag with chipped variants> recipe, so you can always click back through that if you want to see how to make the vanilla item.

I might be interested in working on a PR to implement this, would that be accepted/merged?

**Comment by AlexNijjar** [comment]
You should really just be using the vanilla stonecutter for that; I don't really see a point in generalizing the workbenches, which already have a very specific use. Plus, the recipe tag list system is significantly easier to maintain than something like this.
