### ISSUE TITLE
Mechanist's Workbench z-fighting on neighboring blocks

### ISSUE THREAD

**Issue by AlexisBogue** [CookieCNetwork/Chipped#120]
![image](https://user-images.githubusercontent.com/8432873/160724972-58254c88-ed4c-4b57-a906-023234ec053c.png)

When facing the mechanist's workbench, the upper platform extends beyond the block and produces z fighting issues with the neighboring block.

**Comment by terrariumearth** [comment]
this is being fixed in the next updates, already fixed in 1.18.2, because all the bench models were redone to remove mixeling and z-fighting :)
