### ISSUE TITLE
[1.18.2 Forge] Tables not working for client in multiplayer

### ISSUE THREAD

**Issue by Slunkee** [CookieCNetwork/Chipped#121]
When putting a block into a table for example cobblestone into the mason table, I (the host) can properly use the table, however the other player doesn't get any of the options for the chipped blocks in the table.

**Comment by Slunkee** [comment]
Also broken on dedicated servers, even ones hosted on my own pc

**Comment by terrariumearth** [comment]
https://www.curseforge.com/minecraft/mc-mods/chipped/files/3748664

Fixed in this new version! @Slunkee
