### ISSUE TITLE
[1.18.2 Fabric] Tables not working for client

### ISSUE THREAD

**Issue by DcMbse** [CookieCNetwork/Chipped#122]
Hi there,

same issue as other post about the forge version.
Tables not showing any results when inserting item on dedicated server using chipped-1.18.2-1.2.1-fabric.jar.
So none of the possible chipped items can be crafted.

**Comment by terrariumearth** [comment]
https://www.curseforge.com/minecraft/mc-mods/chipped/files/3748666
 
 Issue fixed here! @DcMbse
