### ISSUE TITLE
Not sure why Connected Texture not working.

### ISSUE THREAD

**Issue by Psychodeus** [CookieCNetwork/Chipped#125]
I used:

- **ConnectedTexturesMod for Fabric** v.0.5.2+1.18.1
- **Indium** v.1.0.2-alpha3+mc1.18.1
- **Chipped** v.1.2

But, still the texture isn't connect. Any suggestion?
And is this mod using CTMF or Chisel?

![2022-04-26_04 26 24](https://user-images.githubusercontent.com/93028949/165170116-5fa9282c-ebcf-4af9-bc19-956a87185f1b.png)

**Comment by terrariumearth** [comment]
CTM added in next update
