### ISSUE TITLE
Stained Glass Panes appear in the `forge:glass` tag

### ISSUE THREAD

**Issue by MuteTiefling** [CookieCNetwork/Chipped#126]
Version: chipped-1.16.5-1.2.1-forge.jar

Issue came up in Enigmatica 6, but I've checked in a limited instance of only JEI, Chipped, and KubeJS to get a read on tags. All the stained glass panes are tagged as `forge:glass`, allowing them to be used as very cheap stand-in replacements for glass in many recipes. 

https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4710

**Comment by terrariumearth** [comment]
1.16.5 is no longer being supported.
