### ISSUE TITLE
Textures aren't connecting

### ISSUE THREAD

**Issue by ghost** [CookieCNetwork/Chipped#131]
Mods

- chipped-1.18.2-1.2.1-forge.jar
- CTM-1.18.2-1.1.4+4.jar
- OptiFine_1.18.2_HD_U_H7.jar

On Forge 1.18.2, playing ATM 7.

![2022-05-27_11 49 12](https://user-images.githubusercontent.com/20939715/170734593-5bc5d094-e2c4-434e-ad3f-24d626ad88d2.png)

**Comment by terrariumearth** [comment]
CTM for most blocks added in new update tb released

**Comment by Nevrai** [comment]
ConnectedTexturesMod is an optional dependency for Chipped, yet Chipped doesn’t have connected textures? When is this going to be added? Would be wonderful!
