### ISSUE TITLE
[Fabric] Mason table is hard to break

### ISSUE THREAD

**Issue by Inurosen** [CookieCNetwork/Chipped#133]
In latest version for Fabric 1.18.2 the Mason Table is as hard as obsidian to break. And it emits purple no texture particles while breaking.

**Comment by Delfite** [comment]
Same issue here, I'm guessing the devs forgot to assign a tool to the Mason Table as well as proper breaking particles unlike the other tables. @grimbop

**Comment by terrariumearth** [comment]
update to 2.0.0 :)
