### ISSUE TITLE
Dark Oak 4 Connected Textures broken

### ISSUE THREAD

**Issue by Serifina** [CookieCNetwork/Chipped#134]
Minecraft 1.18.2
CTM 1.18.2-1.1.4+4
Chipped 1.18.2-1.2.1 - This is downloaded from the page that says it should be 1.2.2
Forge version

Dark Oak connected textures are not working correctly. They produce the purple and black "broken texture" appearance when connected. Specifically Dark Oak 3 and 4. 

Also it looks like the 1.2.1 file was reuploaded for the 1.2.2 version - file is named 1.2.1 and reports 1.2.1 inside Minecraft.

![2022-06-10_21 06 10](https://user-images.githubusercontent.com/8071736/173171928-dcfeee60-7099-4341-a98d-581dbdb759b7.png)

**Comment by SafetyCarrot** [comment]
![2022-06-18_09 29 28](https://user-images.githubusercontent.com/107748752/174429833-2d71f147-5125-4532-aa15-b9119b37b894.png)

I have also experienced this. Dark Oak Planks 4 shown

Minecraft 1.16.5
chipped-1.16.5-1.2.1-forge.jar
Forge version 36.2.34

**Comment by terrariumearth** [comment]
Fixed in next update, with new textures!
