### ISSUE TITLE
Cant Use Workbenches At All

### ISSUE THREAD

**Issue by 888main** [CookieCNetwork/Chipped#139]
Post is exactly as title describes, using vanilla blocks and cannot convert them into the Chipped style blocks

**Comment by 888main** [comment]
![modlist](https://user-images.githubusercontent.com/69447215/180171904-f7e6e0eb-22e2-4f78-b3bc-9c3fb8564e0b.PNG)

**Comment by 888main** [comment]
Above is the modlist we are using, I can see and use workbenches perfectly fine, but my friend who has joined my world cannot use them

**Comment by terrariumearth** [comment]
update to 2.0.0 :)
