### ISSUE TITLE
Connected textures not working

### ISSUE THREAD

**Issue by Nevrai** [CookieCNetwork/Chipped#142]
Connected textures aren’t working for me. Are connected textures for Chipped in 1.18.2 using [ConnectedTexturesMod](https://www.curseforge.com/minecraft/mc-mods/ctm) for Forge not supported? They seem like they should be implemented judging from the CurseForge page.

I am one version behind when it comes to Chipped, but version 1.2.2’s changelog is “Fixed server recipe bug,” so I presume this isn’t the issue.

![2022-08-10_17 20 09](https://user-images.githubusercontent.com/59761487/183943232-f5767558-c1fa-4bb3-a914-265f7467f18b.png)

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Chipped:** 1.2.1
* **ConnectedTexturesMod:** 1.1.4+4

**Comment by deadspidervenom** [comment]
#131

**Comment by terrariumearth** [comment]
hello! all of the connected textures (as well as a better texture revamp) is currently being worked on and to be released soon for 1.16 and 1.18. this issue will be fixed then.

**Comment by Nevrai** [comment]
Okay, that’s good to hear!

**Comment by Nevrai** [comment]
Thanks for adding connected textures! You’re all awesome.
