### ISSUE TITLE
Suggestion: adding slab, stair, wall and column versions

### ISSUE THREAD

**Issue by heyjudek** [CookieCNetwork/Chipped#143]
As the title suggests, what about adding the aforementioned versions of all the available blocks?

**Comment by terrariumearth** [comment]
the new update for the mod that is incoming has close to 10k block variations. to allow the mod to be performant, we will not add these variations of the blocks. however, there are mods that allow you to use a "frame" and apply a block to it. 

there are a few mods that do this, here is one: https://www.curseforge.com/minecraft/mc-mods/framedblocks

**Comment by heyjudek** [comment]
I just realized that this isn't even necessary, at least in my case. You can use chisels and bits to shape them however you want.
