### ISSUE TITLE
[Request] Adding Ukrainian Localization

### ISSUE THREAD

**Issue by AlexFenix33** [CookieCNetwork/Chipped#145]
I have already created file, where I translated name of block for ukrainians. But When i tried to add it to the mod curseforge bans it. Can you add it to your mod's future versions?
[UA_loc.zip](https://github.com/terrarium-earth/Chipped/files/9574527/UA_loc.zip)

**Comment by AlexNijjar** [comment]
These translations are outdated. We will be redoing the entire translation system in a future update with a significantly simplified version. You can update your translations then.
