### ISSUE TITLE
Torches stacking issue when placing and breaking

### ISSUE THREAD

**Issue by FearAK** [CookieCNetwork/Chipped#146]
So whenever I place a torch and break it, it won't merge with my stack again and it seems to write an empty tag element? Someone who tried to help me told me that either chipped or rs gauges might be the problem but I haven't seen anyone else report it?

Do you know if it's your mod that does it or know what could be causing it?

![2022-10-04_17 16 03](https://user-images.githubusercontent.com/46721025/193874078-12f2a5cc-217b-4c4b-87f2-a9892c9a2a51.png)
![2022-10-04_17 23 39](https://user-images.githubusercontent.com/46721025/193874081-95ed5ff2-5988-4c54-b3cc-4714c160acc1.png)
![2022-10-04_17 23 43](https://user-images.githubusercontent.com/46721025/193874084-09269f18-2a89-4977-8f5c-80cad55d0dd0.png)
![2022-10-04_17 44 03](https://user-images.githubusercontent.com/46721025/193874088-5de5fdcc-2c68-47c0-a321-75c4b4fb24d4.png)
![2022-10-04_17 15 54](https://user-images.githubusercontent.com/46721025/193874091-87920709-954e-412b-9137-a965a5950611.png)

**Comment by FearAK** [comment]
It also happens with torches I find it loot btw, they won't stack with my crafted ones.

**Comment by StarBeard13** [comment]
Same here

**Comment by AlexNijjar** [comment]
What version are you playing on? does this happen on chipped 2.0.0?

**Comment by AlexNijjar** [comment]
This shouldn't happen on the latest version so I'll close it if no one else is having this issue
