### ISSUE TITLE
(Forge 1.18.2 - 2.0.0) Crash on Launch

### ISSUE THREAD

**Issue by PhweeDev** [CookieCNetwork/Chipped#147]
Hello,

I just updated to 2.0.0. and I get greeted with a crash on start-up. Can you look into this?

Report: https://paste.gg/p/anonymous/ea333422c6b64954b4e5ced4a74d2bba
Log:  https://paste.gg/p/anonymous/ed6078c7bd00429e935b689fd0e29a8a

**Comment by terrariumearth** [comment]
Do you have Rubidium in this modpack?

**Comment by terrariumearth** [comment]
Rubidium is not compatible with CTM, and it is an issue on the Rubidium side. There is nothing we can do about that it, sadly. Remove Rubidum if you want to be able to use Chipped :(.

**Comment by PhweeDev** [comment]
That's unfortunate. I wonder why it didn't crash with the version prior to 2.0.0. Probably code changes. Either way, thanks for your help!

**Comment by PhweeDev** [comment]
Are you sure it's actually **just** Rubidium causing this? I've got a separate instance with CTM, Chipped 2.0.0, Rubidium, Rubidium Extras, and a couple other mods. and my game and worlds load up perfectly fine. I'm just confused as to why they work in a pack with smaller amounts of mods, but for some reason fail in the large scheme.  Here's the mods on this separate instance.  I should note I had CTM in the massive pack before updating to Chipped 2.0.0.
![image](https://user-images.githubusercontent.com/44146422/194709561-602f5ba7-531e-4fea-9942-c94c26c04152.png)

**Comment by PhweeDev** [comment]
So after messing around for a while. I figured out that it was some resource pack that I had loaded for some reason causing issues. Issue solved.
