### ISSUE TITLE
(Forge 1.18.2 - 2.0.0) Crash right at the end of startup

### ISSUE THREAD

**Issue by notWaterGuy12** [CookieCNetwork/Chipped#148]
Rubidium/Optifine are not present. Forge version 40.1.51. Everything was fine before the update, not sure what could be going wrong.

Crash report: https://pastebin.com/YEvWLhQX

**Comment by terrariumearth** [comment]
This seems to be a CTM issue, we can't fix the issue as it does not seem to be on us. :( Report it to CTM.

**Comment by notWaterGuy12** [comment]
Upon searching the CTM issues pages, this appears to be a problem with my forge version for anyone else having this issue. I'm stuck on this forge version because I've been playing with Vivecraft, but hopefully my discovery helps someone else :D
