### ISSUE TITLE
Does not work with ProjectE/Breaks Existing ProjectE Worlds (1.18.2-2.0.0)

### ISSUE THREAD

**Issue by MystiaTech** [CookieCNetwork/Chipped#149]
We had Chipped working with a previous version of our pack with ProjectE and ProjectE Integration. 

When we updated to 2.0.0, we lost all EMC values, completely rending ProjectE useless

Is there anyway to fix this?

**Comment by PhweeDev** [comment]
Same here. ProjectE is completely broken even on a new world. and the EMC system cannot be used at all.  This only happens when updating to 2.0.0 of Chipped Forge.

**Comment by PhweeDev** [comment]
I can actually confirm, @Advtech92 that it's ProjectE Integration's fault. I have opened an issue on their page, hoping for them to respond and update with a fix for it.

**Comment by MystiaTech** [comment]
ProjectE Integration has since fixed this so I'll close it.
