### ISSUE TITLE
CTM not wroking as expected

### ISSUE THREAD

**Issue by AdeptusAutumn** [CookieCNetwork/Chipped#150]
The new CTM seems to be borking about. Tested it mainly with Glass panes but found one with stone as well.
Video of the buggynes in action https://youtu.be/KWI2O8EM4JY
[latest.log](https://github.com/terrarium-earth/Chipped/files/9739990/latest.log) if it helps

**Comment by terrariumearth** [comment]
With CTM and Chipped installed, both of these connected textures work as they should. However, you seem to have Rubidium in your modpack. That is known to have issues with CTM, and it is not something we can control. I recommend removing Rubidium from your pack, and if the issue persists, open this issue back up. Thank you!
