### ISSUE TITLE
Name Mismatch/Texture Mismatch

### ISSUE THREAD

**Issue by MystiaTech** [CookieCNetwork/Chipped#152]
Running 2.0.0 of Chipped and we were looking through the doors, we noticed that the spruce, crimson, and warped doors may have a misnamed doors/mistexturing. The secret door does not have the bookshelf texture like the oak, dark oak and jungle doors do. It seems to be from the spruce doors on.

**Comment by terrariumearth** [comment]
Yeah.. we are aware of this issue. Its a name mismatch :( It will be fixed next update, my bad 😭

**Comment by JAWredstoneguy** [comment]
The doors aren't the only ones with naming issues, there are examples of naming issues throughout the chipped blockset.
