### ISSUE TITLE
Connected Textures Refabricated is Broken

### ISSUE THREAD

**Issue by JuliyJulius** [CookieCNetwork/Chipped#153]
I know this isn't a surprise anymore, but I noticed that, no matter the mods we put, the CTM Refabricated Mod doesn't works at all. What makes it even weirder is the fact that it usually worked before I started adding/updating the mods.
[latest.log](https://github.com/terrarium-earth/Chipped/files/9758921/latest.log)
The latest log is included for further context.
Hopefully this issue will be noticed by the developers.

**Comment by Fade-Alchemist** [comment]
Having the same problem-->

Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode

**Comment by terrariumearth** [comment]
@CodexAdrian

**Comment by AlexNijjar** [comment]
Looks like an incompatibility with Iris. Try the latest iris version and lmk if it's still crashing
