### ISSUE TITLE
[Suggestion] Add item for customizing blocks or a universal table

### ISSUE THREAD

**Issue by Nevrai** [CookieCNetwork/Chipped#154]
I’m a huge fan of Chipped, but a big gripe I have with it is that having to use seven different tables for different kinds of blocks is a bit unintuitive. It creates clutter, and it makes designing take longer. It’s also a bit frustrating as you have to look for the right table for the specific block you want to customize, which usually, at least in my case, takes a little while.

I was wondering if you could add a portable tool, similar to what [Chisel](https://www.curseforge.com/minecraft/mc-mods/chisel) and [Re-chiseled](https://www.curseforge.com/minecraft/mc-mods/rechiseled) have, that lets you customize any Chipped-supported block on the go, without having to use a specific table. This would let you not only customize blocks portably with just an item but also remove the requirement of having to use seven different tables.

I’m a big fan of the new 2.0.0 update, with all the new blocks and the beautiful connected textures, and if this could be added, Chipped would be even better! It could be a config option if you don’t want to enable this by default, but if this could be implemented, that’d be absolutely wonderful. Even if you don’t want to add an item, it’d still be great if you could at least add a config option to use one “universal” table rather than different types.

**Comment by AlexNijjar** [comment]
Universal tables have been added in 1.20.4
