### ISSUE TITLE
Errors to load forge whit mods and plugins 

### ISSUE THREAD

**Issue by Trampa3** [CookieCNetwork/Chipped#155]
19.10 19:33:55 [Server] main/ERROR [mixin/]: Mixin config chipped-common.mixins.json does not specify "minVersion" property
19.10 19:33:55 [Server] main/ERROR [mixin/]: Mixin config chipped.mixins.json does not specify "minVersion" property

**Comment by AlexNijjar** [comment]
these errors don't mean anything. can you send the log?
