### ISSUE TITLE
Blocks with connected textures are invisible through portals/water with Sodium installed

### ISSUE THREAD

**Issue by NatSquared** [CookieCNetwork/Chipped#156]
Modlist:
```chipped-2.0.0-fabric.jar
ctm-fabric-1.0.0+1.18.jar
fabric-api-0.59.1+1.18.2.jar
indium-1.0.7+mc1.18.2.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
```
Place blocks that make use of the Connected Textures mod (e.g Polished Calcite)

View the block through a Nether Portal or through the top portion of flowing water. It will appear invisible and x-ray through the ground.

![2022-10-20_21 20 06](https://user-images.githubusercontent.com/33235902/197111311-e6343657-0aba-4358-8b2d-a7bc3865d865.png)
![2022-10-20_21 20 27](https://user-images.githubusercontent.com/33235902/197111315-21fb0fe3-2194-4d19-9e28-46a27bdfde1b.png)

**Comment by AlexNijjar** [comment]
can you make an issue on the ctm refabricated GitHub?
