### ISSUE TITLE
workbenches doesn't work on my server

### ISSUE THREAD

**Issue by AlaseelGo** [CookieCNetwork/Chipped#157]
the issue is the workbenches doesn't work in my server 
I can craft the bench but when I put the block it doesn't show me the new blocks or the mod blocks 
how can I fix it ?

**Comment by terrariumearth** [comment]
What update are you on?

**Comment by AlaseelGo** [comment]
> What update are you on?

1.18.2

**Comment by AlexNijjar** [comment]
Does it just show an empty gui? For every block? What's the chipped version, mod loader, and mod list?

**Comment by AlaseelGo** [comment]
> Does it just show an empty gui? For every block? What's the chipped version, mod loader, and mod list?

yes it shows an empty gui for every block , the chipped ver is 1.2.1 , the mod loader is forge 
and this is the mod list :
[mods.txt](https://github.com/terrarium-earth/Chipped/files/10294048/mods.txt)

**Comment by AlexNijjar** [comment]
we don't support old chipped versions. please update to chipped 2.0.0
