### ISSUE TITLE
Some inconsistencies in textures for glass pane 7

### ISSUE THREAD

**Issue by Porcy** [CookieCNetwork/Chipped#158]
![2022-10-29_16 07 53](https://user-images.githubusercontent.com/8096340/198850746-15da6243-4c89-43f0-9ca9-bfe435f7c590.png)
![2022-10-29_16 07 57](https://user-images.githubusercontent.com/8096340/198850747-65316e09-09a5-4adc-bb28-a09f407a4509.png)
It looks like a directional issue.

**Comment by Porcy** [comment]
Another one:
(Depends from which side you look)
![2022-11-03_13 41 18](https://user-images.githubusercontent.com/8096340/199795684-e462025b-6c01-4c15-ae62-92eade7cfebf.png)
![2022-11-03_13 41 24](https://user-images.githubusercontent.com/8096340/199795706-14765aa9-9cf1-487e-b886-be8d9e2c6c94.png)

**Comment by SrRapero720** [comment]
No only GLASS_PANE_7 also GLASS_7 have the same inconsistences
![image](https://user-images.githubusercontent.com/29090346/200086597-5be65e86-aa78-4a5b-b050-8f35063d6cd4.png)

**Comment by SrRapero720** [comment]
A lot of blocks
![image](https://user-images.githubusercontent.com/29090346/200086768-7ca91c80-fa8a-4d3a-a0e5-21112adea9c8.png)

**Comment by terrariumearth** [comment]
Yeah... All glass panes seem to have this problem when we added CTM. We are looking into a fix for both issues, sorry for the inconvenience! Connected textures do be funny sometimes.

**Comment by WordStormRose** [comment]
It seems all of the blocks with connected textures are bugged; several of the stone types randomly connect/disconnect when other blocks are placed around them.

**Comment by SrRapero720** [comment]
is still present in 1.18.2?

**Comment by WordStormRose** [comment]
Yes, last time I looked. If there's a recent update then I haven't seen it with the update yet.

**Comment by FlynnLies** [comment]
> It seems all of the blocks with connected textures are bugged; several of the stone types randomly connect/disconnect when other blocks are placed around them.

Bit late, but had the same problem. Seems to be bc of Rubidium, see [CTM#168](https://github.com/Chisel-Team/ConnectedTexturesMod/issues/168). You can press F3+A to temporarily fix it. This issue is not related to that however, since that does nothing for panes.
