### ISSUE TITLE
Updated from 1.18.1 to 1.18.2 Now Some Textures Are Wrong

### ISSUE THREAD

**Issue by aunrea** [CookieCNetwork/Chipped#159]
I had to update my 1.18.1 world to 1.18.2. Now some of the Chipped blocks I made in 1.18.1 are showing as pink and black checker blocks. Not all blocks have this issue. Just some glass, green tinted glass, and green terracotta that were modified using Chipped. Is there a way to fix this or do I need to replace all those blocks?

**Comment by aunrea** [comment]
Actually many of the textures appear to be missing. Is there a way to add the missing textures? I am not sure how to add missing textures, most of the info I find when I search is that missing textures are usually due to resource packs. I haven't found a way to fix it for a mod.

**Comment by aunrea** [comment]
Turns out it's not compatible with sodium

**Comment by terrariumearth** [comment]
The change between 1.18.1 and 1.18.2 for Chipped was drastic in terms of content. We updated and changed all textures of blocks, as well as added thousands of new ones. I really recommend from this point forward you only use the new 1.18.2 version on new worlds, or it is likely that this stuff will happen. I apologize for the inconvenience, but the overall quality of the mod depended on this update :(. As for sodium, it is a common problem for mods like Sodium to not play nice with CTM, which is a necessity for the new version of Chipped. If there are any other issues, please reopen the ticket and I will be happy to help. Sorry I couldn't give you a better solution :(.
