### ISSUE TITLE
Special Lantern are not craftable

### ISSUE THREAD

**Issue by Sunekaer** [CookieCNetwork/Chipped#160]
Minecraft: 1.18.2
chipped-2.0.0-forge.jar

No way of crafting Special Lantern, if you cheat on in and put it in there tinkerers table, first outcome is air
![billede](https://user-images.githubusercontent.com/18720460/200584348-b8851afc-760a-4350-bfcd-d97543ef525f.png)

**Comment by AlexNijjar** [comment]
Will be fixed in the next release
