### ISSUE TITLE
Use Continuity instead of CTM Refabricated for Fabric version

### ISSUE THREAD

**Issue by cody-quinn** [CookieCNetwork/Chipped#162]
In the Fabric ecosystem Continuity is used far more than CTM Refabricated. Requiring a mod that has the same functionality as another but is much much less common in the ecosystem and is incompatible is a weird and silly decision.

**Comment by lamoyrl90** [comment]
CTM and Continuity use different methods for implementing connected textures. I imagine it would take quite a bit of work to do this.

**Comment by lxly9** [comment]
continuity utilizes the default optifine implementation

**Comment by seeruk** [comment]
I also thought this was a slightly odd decision, I can appreciate Chipped is where it is now, but Continuity is the mod that most people will probably want to have installed, particularly if they're moving from OptiFine over to a bunch of mods that provide the same functionality.

To add something to the discussion at least, it does look like you can use both Continuity and CTM Refabricated at the same time?

**Comment by AlexNijjar** [comment]
It's currently not possible for us to use Continuity as it lacks some of the CTM features and does not have a forge version.
 
We've been speaking with the developer of Continuity and that might be a viable option in the future, but for right now CTM is the only game in town to do what we need.
