### ISSUE TITLE
chipped 2.0.0 works on fabric 1.19 but has errors

### ISSUE THREAD

**Issue by Tors-0** [CookieCNetwork/Chipped#164]
even though the mod launches fine and doesnt throw errors as long as you have ctm for 1.19 installed, once in the world you are unable to interact with any of the workbenches, this is unfortunate as i was planning to use it on a server i'm hosting but just discovered this problem

**Comment by AlexNijjar** [comment]
this is because the component code (text on screen) changed in 1.19. Chipped is not available for 1.19 yet, so even though it runs, you should not be playing the 1.18 version on 1.19.

We will be releasing a 1.19 version eventually
