### ISSUE TITLE
Glass textures not working in Fabric 1.18.2

### ISSUE THREAD

**Issue by Blosom2063** [CookieCNetwork/Chipped#166]
### Bug Description

Some textures, mostly glass textures are not working in Fabric 1.18.2. They're appearing as the pink and black checkered blocks. This is also applying to the glass panes, which despite appearing fine in the inventory when placed down go back to the pink and black block. I have the recourse pack CTM overhaul, along with lots of other mods and one other resource pack that doesn't appear to be affecting it

### Version

2.0.1

### Mod Loader Version

0.14.12-1.18.2

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
do you have sodium? you need indium as well

**Comment by Blosom2063** [comment]
I have sodium, is Indium a mod or resource pack?

**Comment by Blosom2063** [comment]
> do you have sodium? you need indium as well

That worked thank you!
