### ISSUE TITLE
[Bug]: Default Terracotta has no Mason Table recipes

### ISSUE THREAD

**Issue by eclairo** [CookieCNetwork/Chipped#168]
### Bug Description

Placing the default colored terracotta in the mason table workbench has no Craftable variants.

chipped:terracotta is not in mason_table.json

Tried to add chipped:terracotta into mason_table.json and still not craftable

### How to Reproduce?

Place default coloured terracotta into mason table

### Expected Behavior

Can craft default color terracotta varians using the mason workbench. The blocks are in the game.

### Version

2.0.1

### Mod Loader Version

1.18.2

### Mod Loader

Quilt

**Comment by TheBaggBoy** [comment]
Still an issue in 1.20.1
