### ISSUE TITLE
[Bug]: Game Crashes when viewing Chipped blocks in JEI

### ISSUE THREAD

**Issue by tazzy989** [CookieCNetwork/Chipped#169]
### Bug Description

When scrolling through many JEI pages, as soon as I attempt to scroll to the page where Chipped blocks begin, the game crashes. I am making a HUGE modpack, so very likely something here is just not playing nice with Chipped. 

### How to Reproduce?

Step 1: Create needlessly large modpack
Step 2: Scroll through JEI
Step 3: death

### Expected Behavior

To see pretty blocks while scrolling through JEI. 

### Version

chipped-forge-1.18.2-2.0.1

### Mod Loader Version

40.2.0

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/h6WMBFch

**Comment by AlexNijjar** [comment]
it looks like a ctm issue. you should report it to them
