### ISSUE TITLE
[Bug]: Decorative ice cube texture error

### ISSUE THREAD

**Issue by AltoClef6115** [CookieCNetwork/Chipped#170]
### Bug Description

When chipped is used with fabric-seasons, ice blocks in chipped will turn into black and purple blocks.Then all the ice cubes in chipped will be named chipped:seasonal_ice，Maybe it's a conflict somewhere, but I'm not quite sure what's going on.

### Expected Behavior

Maybe I'll have to ask you or the author of fabric-seasons to make them compatible

### Version

2.0.1

### Mod Loader Version

 1.18.2 

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
it’s an issue on their side. they do something very wacky with their seasonal ice registration  that breaks chipped ice. we’ve talked to the dev about it but I guess they haven’t fixed it yet. best thing to do is make an issue on their github

**Comment by AltoClef6115** [comment]
Thanks for your answer, I have raised an issue on their github but don't know when it will be resolved
