### ISSUE TITLE
[Bug]: Forge 1.19.2: Chipped Lanterns Generate Water Sourceblocks when part of Create cart contraption

### ISSUE THREAD

**Issue by SteelChikorita** [CookieCNetwork/Chipped#173]
### Bug Description

With the latest versions of both Create and Chipped on 1.19.2 forge, chipped versions of lanterns that become part of a cart contraption create water source blocks where they were previously placed.

### How to Reproduce?

1. Enter a 1.19.2 world with the latest versions of Create and Chipped.
2. Put chipped lanterns onto a linear chassis and connect them to it with slime.
3. Put down a redstone powered cart assembler on the rail line under the linear chassis, send a cart in.
4. Watch as water source blocks are formed where the lanterns were placed before.

### Expected Behavior

It is expected behavior that water source blocks do not form where lanterns were placed when they become part of a cart contraption.

### Version

2.1.0

### Mod Loader Version

Forge 1.19.2 - 43.2.3

### Mod Loader

Forge

**Comment by P3rf3ctXZer0** [comment]
Do you use Oh The biomes? I have only seen this when that mod is present.

**Comment by SteelChikorita** [comment]
I do not have Oh The Biomes You'll Go or any other biome-changing mod installed on this specific modded instance.
