### ISSUE TITLE
[Bug]: Extremely long loading time

### ISSUE THREAD

**Issue by Herobattler** [CookieCNetwork/Chipped#174]
### Bug Description

Extremely long loading time, more then a minute of extra loading time with the latest 1.19.2 release of this mod on forge.

### How to Reproduce?

Add the latest 1.19.2 forge release of this mod into the mods folder.

start the game.

### Expected Behavior

Regular loading time.

### Version

2.1.0

### Mod Loader Version

43.1.52

### Mod Loader

Forge

**Comment by P3rf3ctXZer0** [comment]
Wait it is taking less than 2 mins for me and I have a metric ton of mods... what mods do you have? Please share your complete modlist by using this command if on windows. https://www.howtogeek.com/98064/how-to-print-or-save-a-directory-listing-to-a-file/
