### ISSUE TITLE
[Feature Request]: Make CTM an optional dependancy

### ISSUE THREAD

**Issue by ground-fruit** [CookieCNetwork/Chipped#175]
### Is your feature request related to a problem?

One of CTM's config options is to disable connected textures entirely.
It seems silly to have to install a whole mod to disable the feature.

_I know very little about the internals of these mods or if this is feasible._

### Solution(s)

Suggestion: Make CTM an optional dependency, and load Chipped's un-connected textures when CTM is not installed.

### Describe alternatives you've considered

Disabling connected textures is a solution to the incompatibility with Supplementaries:
https://github.com/CodexAdrian/ConnectedTexturesMod-Fabric/issues/1

### Mod Version

Chipped Fabric 2.1.0

CTM Fabric 1.0.0 1.19.2

Supplementaries 1.19.2-2.2.50

### Mod Loader Version

Fabric 1.19.2 - 0.14.13

### Mod Loader

Fabric

**Comment by Lunarck** [comment]
I'm also dealing with this issue and sadly this fix isn't working. I tested it on a clean world as well. If you know any other way, I'd love to know, thank you!

**Comment by ground-fruit** [comment]
> I'm also dealing with this issue and sadly this fix isn't working. I tested it on a clean world as well. If you know any other way, I'd love to know, thank you!

Did you restart the game entirly after disabeling CTM? You’ll need to do this because the error has to do with the registry, which is not reloaded with f3+T (Devs, correct me if I’m wrong)

**Comment by Lunarck** [comment]
I did. I set Disable CTM to TRUE and the texture still continues to be missing on my clean world. I'm not sure why.

Chipped 2.1.1

CTM Fabric 1.0.0

Fabric API 0.75.1

MoonlightLib 2.2.13

Resourceful Lib 1.1.22

Supplementaries 2.2.53

**Comment by AlexNijjar** [comment]
it's made a required dependency as many of chipped's blocks are broken without it. technically you don't need it but we don't want people downloading it to be confused when many of the blocks have broken textures

**Comment by Lunarck** [comment]
Can this issue be fixed?

I asked about this in the Supplementaries Discord and the developer said it was an issue with CTM Fabric.

**Comment by LucasOe** [comment]
On Fabric you can override the dependents yourself inside `config/fabric_loader_dependencies.json`:
```json
{
  "version": 1,
  "overrides": {
    "chipped": {
      "-depends": {
        "ctm" : "IGNORED"
      }
    }
  }
}
```

**Comment by Lunarck** [comment]
Thank you, I will try this!

**Comment by Lunarck** [comment]
So far it has been working in my game! Thank you so much!

**Comment by CodexAdrian** [comment]
Seems as though you found a solution. CTM will continue to be a required dependency as many of our blocks do not work without it. The issue with rendering is not on chipped, but on CTM for Fabric, which I will address.
