### ISSUE TITLE
[Feature Request]: JEI/REI Filter

### ISSUE THREAD

**Issue by Wubzzz1337** [CookieCNetwork/Chipped#177]
### Is your feature request related to a problem?

JEI/REI is just very full already in my eyes, so filtering out some Varies by default via an option would be great.

### Solution(s)

As described above, filter most of them out, and only show 1 Type with the different variations.

### Mod Version

Latest

### Mod Loader Version

1.19.2 - Latest

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
that's not something we can do
