### ISSUE TITLE
[Bug]: Missing candle texture in Wrought Iron Lantern

### ISSUE THREAD

**Issue by EdrikP** [CookieCNetwork/Chipped#178]
### Bug Description

In the hanging variant of chipped:wrought_iron_lantern the candle seems to be missing inside the lantern.

### How to Reproduce?

Obtain chipped:wrought_iron_Lantern.
Place on underside of a block.

### Version

2.1.1

### Mod Loader Version

43.2.6

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
Fixed in 3.0.2
