### ISSUE TITLE
[Bug]: Ice Tags Issues - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [CookieCNetwork/Chipped#179]
### Bug Description

So much different ice tags issues in the console.
Game start takes longer cause of them.

I've read the closed issues and in some posts someone said its cause of "Fabric Seasons".
Still the case here?

### Version

2.1.1

### Mod Loader Version

1.19.2 - 0.14.17

### Mod Loader

Fabric

### Logs or additional context

https://gist.github.com/SpigotDE/d0099a679ba90a621d9fbbd626f7c789

**Comment by AlexNijjar** [comment]
yes it’s fabric seasons that breaks chipped ice. they change the id of the vanilla ice block which breaks the chipped ice registration. We’ve talked to them about it but they haven’t fixed it yet.
