### ISSUE TITLE
[Feature Request]: Port to 1.19.3

### ISSUE THREAD

**Issue by myron-obsolete-account** [CookieCNetwork/Chipped#182]
### Is your feature request related to a problem?

N/A

### Solution(s)

Could you update this mod to 1.19.3 please? Thanks.

### Describe alternatives you've considered

N/A

### Mod Version

N/A

### Mod Loader Version

N/A

### Mod Loader

N/A

### Additional context

N/A

**Comment by AlexNijjar** [comment]
when ctm updates

**Comment by AlexNijjar** [comment]
skipping 1.19.3 and going straight to 1.20
