### ISSUE TITLE
[Bug]: Botanist Workbench not showing recipes output for Glass (maybe other items?).

### ISSUE THREAD

**Issue by WillianBK** [CookieCNetwork/Chipped#183]
### Bug Description

Can't find a way to make it work, so it should be a bug.
When you open the Botanist Workbench and put glass or glass panes it doesn't give you an output.

### How to Reproduce?

Open botanist workbench GUI.
Drag the glass or glass pane to the input slot.
No output is show to you to click.

### Expected Behavior

Show the items i could select and chose.

### Version

2.1.1

### Mod Loader Version

1.19.2 - 0.14.17

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
you're supposed to put glass in the glassblower, not the botanist workbench

It looks like REI is wrong
