### ISSUE TITLE
[Bug]: Glass panes/fences/iron bars connecting to Chipped Leaves

### ISSUE THREAD

**Issue by ZaihnDT** [CookieCNetwork/Chipped#184]
### Bug Description

Been trying to make some leaves patches near glass panes, they connected for some reason. 

### How to Reproduce?

1. Place a Glass Pane, Fence or Iron Bars, or any connectable block
2. Place any leaves from Chipped
3. See it's behaving like a full/solid block other blocks are connected to.
4. You can confirm other leaf blocks from vanilla not behaving like that

### Expected Behavior

Connected blocks should be not connecting I guess.

### Version

2.1.1

### Mod Loader Version

1.19.2 - 43.2.4

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
Fixed
