### ISSUE TITLE
[Bug]: Glass seethrough bug with amethyst blocks

### ISSUE THREAD

**Issue by toffi3** [CookieCNetwork/Chipped#185]
### Bug Description

As in the title basically
Here's the showcase, my mod list and resource pack list : https://www.youtube.com/watch?v=5oCr5AKDhTg

### How to Reproduce?

1. Do what i do on the video basically

### Version

1.18.2

### Mod Loader Version

1.18.2 0.14.2

### Mod Loader

Fabric

**Comment by gusthemouse** [comment]
i have this issue to in 1.19.2, only select blocks load in and trying to search for them in the JEI menu via name or scrolling will softlock the game by not allowing you to move/edit the menu or access your inventory anymore. It's very strange and pretty much game breaking

**Comment by AlexNijjar** [comment]
1.18.2 is no longer supported and it's probably something with CTM, which we have replaced in modern versions with [Athena](https://modrinth.com/mod/athena-ctm)
