### ISSUE TITLE
[Feature Request]: Optional dependency on CTM Refabricated

### ISSUE THREAD

**Issue by Lgmrszd** [CookieCNetwork/Chipped#187]
### Is your feature request related to a problem?

CTM Refabricated is currently causing issues with other mods:
https://github.com/CodexAdrian/ConnectedTexturesMod-Fabric/issues/7
But Chipped is requiring CTM to be present on client.

### Solution(s)

Have CTM as optional dependency. While not providing connected textures, it would still be acceptable compromise.

### Describe alternatives you've considered

Use Continuity mod instead of CTM Refabricated:
Not feasible as it is using different format than CTM and is Fabric only, would require to maintain both formats for both loaders: #162

### Mod Version

2.1.2

### Mod Loader Version

1.19.2 - 0.14.17

### Mod Loader

Fabric

**Comment by M0nkeyPr0grammer** [comment]
This would be a great feature, I did notice that continuity will also allow some connected textures that work with Chipped Fabric

**Comment by AlexNijjar** [comment]
CTM is no longer used.
