### ISSUE TITLE
[Bug]: Regular Terracotta cannot be chipped in the masons workbench

### ISSUE THREAD

**Issue by a-molokodrengo** [CookieCNetwork/Chipped#188]
### Bug Description

All other types of terracotta work beautifully, for some reason the regular terracotta recipes don't exist.  When I had JEI installed they would not show up like they don't exist in game.  I noticed an issue basically the same that was closed 3 weeks ago, but no info on a fix.  Appreciate it! great mod!

### How to Reproduce?

Created a clean 1.18.2 install, added just chipped and CTM with forge 40.2.0 (also tried forge 40.2.1 just in case).  Started new world, gave myself terracotta and the masons workbench.  Nothing could be done to it

### Expected Behavior

All recipes to exist

### Version

2.0.1

### Mod Loader Version

40.2.0

### Mod Loader

Forge

### Logs or additional context

n/a

**Comment by AlexNijjar** [comment]
this was fixed in 1.19 but not 1.18 because we don’t support that version anymore. if there’s some other major 1.18 bug i can update it and backport that fix though.

**Comment by a-molokodrengo** [comment]
ahh understood, I should be able to add these somehow if I understand correctly.  The forge link in the wiki for adding tags is dead

**Comment by AlexNijjar** [comment]
you can make a data pack, copy this file https://github.com/terrarium-earth/Chipped/blob/1.18.2/common/src/main/resources/data/chipped/tags/items/terracotta.json

and then paste it into "my_datapack/data/chipped/tags/items/terracotta.json"

**Comment by a-molokodrengo** [comment]
amazing, thank you so much
