### ISSUE TITLE
[Bug]: Glass panes texture is wrong on one side

### ISSUE THREAD

**Issue by FlynnLies** [CookieCNetwork/Chipped#190]
### Bug Description

Glass panes render only one direction correctly. This direction is consitent in the world and every pane added by chipped has this problem. This is especially annoying with panes that are 1 or 2 wide.

![2023-03-22_23 12 20](https://user-images.githubusercontent.com/93095631/227051994-7df30273-3014-413d-8304-a6b841590804.png)
![2023-03-22_23 12 13](https://user-images.githubusercontent.com/93095631/227052003-a1faf822-70b0-48d7-8b29-932dab865e3e.png)

Turning it 90° will give the same result.

### How to Reproduce?

1. Take any glass pane added by chipped
2. Place them as seen above
3. Inspect both sides

### Expected Behavior

They should look the same on both sides.

### Version

2.1.2

### Mod Loader Version

1.19.2 - 43.2.4

### Mod Loader

Forge

### Logs or additional context

This problem was already mentioned in #158 but only for 1.18

**Comment by Quest79** [comment]
This is present in tons of blocks. The edge detection code to drive where boarders are is completely buggy or it is being conflicted somehow by something else. Rubidium maybe? It kind of ruins the entire mod for me. 
 


![javaw 032523 194049 🍙 2560x391](https://user-images.githubusercontent.com/635094/227752346-0bedb2b6-07ad-4d57-99d5-cd03fa9b8377.png)

**Comment by FlynnLies** [comment]
This is a different issue, you can just press F3+A to reload the chunks and it should work. Until you place more blocks.

Doesn't work for glass panes.

**Comment by AlexNijjar** [comment]
We'll be switching to [Athena](https://modrinth.com/mod/athena-ctm) in 1.20 and onwards so it'll fix these kinds of rendering issues.

<img width="1512" alt="Screenshot 2023-07-05 at 5 21 21 AM" src="https://github.com/terrarium-earth/Chipped/assets/61668546/92404d12-24f7-464d-9f42-c5b3e97afdc2">
