### ISSUE TITLE
[Bug]: Error Loading chipped into custom modpack 

### ISSUE THREAD

**Issue by JackPPember03** [CookieCNetwork/Chipped#191]
### Bug Description

I have tried loading chipped into a custom modpack I am using, and I get these 2 errors that require me to install additional files. I tried finding them on my own but have either not installed them properly or haven't found the right files. There also isn't any links to the files listed in the image attached unless I've missed the link on your curseforge page.  

Assistance would be much appreciated as I am incredibly lost.

The file in my mods folder reads: chipped-forge-1.19.2-2.1.2.jar

![Screenshot (64)](https://user-images.githubusercontent.com/128728781/227269921-6c92afed-e06c-414b-9d4a-c6815d7fc11d.png)

### Version

1.19.2-2.1.2

### Mod Loader Version

43.2.4

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
you can find the dependencies here https://www.curseforge.com/minecraft/mc-mods/chipped/files/4434885
<img width="437" alt="Screenshot 2023-03-23 at 11 36 10 AM" src="https://user-images.githubusercontent.com/61668546/227272764-0ca42677-aedb-416d-9cab-b110ed7c9b2c.png">
