### ISSUE TITLE
[Feature Request]: [Translation] I attempted to make a chinese translation for your mod

### ISSUE THREAD

**Issue by Kirisoup** [CookieCNetwork/Chipped#193]
### Is your feature request related to a problem?

So I was playing with my Chinese friends with this mod, who cannot understand English...

### Solution(s)

therefore I decided to make an entire translation of your mod!

I hope you qppreciate it! I actually really like your mod, and I decided to do my part to try and maybe polish it a little bit? And if you would like to, please consider maybe adding my translation into your next update! <3

[zh_cn.zip](https://github.com/terrarium-earth/Chipped/files/11079104/zh_cn.zip)

### Mod Version

2.1.3

### Mod Loader Version

1.19.2 - 0.19.0-beta.2

### Mod Loader

Quilt

### Additional context

I am actually not sure if this is the appropriate place to post it, like normally it should be a PR? But I don't know how to pull a PR. If this make things less convinient, I'm sorry ; ; 

Also, I have to admit that the translation is done with the help of **machine translation** - I mean, there is like 6.7k+ blocks that need to be translate, it is litterally impossible to do all the work only by manual. Nevertheless I still made a lot of effort trying to make sure that most of the blocks actually have comprehendable and consistent names, but it might sometimes feels a bit wierd for native Chinese speakers - at least it is a good start though? 

(o゜▽゜)o☆

**Comment by CodexAdrian** [comment]
If you could please make a PR with these changes so you get proper credit and so we dont have to download an unverified Zip file it'd be much appreciated

**Comment by Kirisoup** [comment]
> If you could please make a PR with these changes so you get proper credit and so we dont have to download an unverified Zip file it'd be much appreciated

Sorry, need help, I'm dumb
So should I put the zh_cn.json file at `forge/src/generated/resources/assets/chipped/lang`?

I tried to build the mod with `./gradlew build` but the jar files I get only has an META-INF thing in it and nothing else, so I cannot tell if I'm doing it right or wrong💦

**Comment by Kirisoup** [comment]
#194
