### ISSUE TITLE
[Bug]: Incompatibility with Every Compat

### ISSUE THREAD

**Issue by CritFlaw** [CookieCNetwork/Chipped#195]
### Bug Description

It seems that in the 2.1.3 release in 1.19.2 Forge, the mod does something weird with Every Compat and potentially messes the order of items registered. In order to make a mangrove storage drawer, the JEI recipe shows I need to use nailed mangrove planks instead of the default vanilla planks. It would be fine if the recipe also allowed for that variant as part of the tags, but currently it's a bit annoying to have to use chipped to transform those planks to nailed variants just to craft the storage drawer. 

### How to Reproduce?

1. Install Chipped, Storage Drawers, Framed Compacting Drawers, Every Compat, and JEI
2. Look at the recipe for the mangrove 1x1 drawer

### Expected Behavior

Recipes should use either the base material item, or the generic tag version that accepts any of them, not a specific chipped variant of a given block. 

### Version

2.1.3

### Mod Loader Version

Forge 1.19.2 - 43.2.6

### Mod Loader

Forge

### Logs or additional context

https://gist.github.com/CritFlaw/ab92bbcc99ac4677814a53ac6eeaad26 - latest.log

**Comment by RedBeast1959** [comment]
Every compat doesn't support vanilla mincraft mangrove wood. Go check it without Chpped.

**Comment by AlexNijjar** [comment]
^
