### ISSUE TITLE
[Bug]: chipped doesn't seem to work for HP on our server, but it works on Apple MacBook

### ISSUE THREAD

**Issue by beandogs** [CookieCNetwork/Chipped#197]
### Bug Description

The server admin gets kicked off server and immediately crashes every time a block that connects textures (e.g. deepslate offset bricks) appears anywhere in the world, whether I hold it or place it, I can see it and interact with it just fine but he can't. Our other player plays on an HP and I use Apple MacBook. I am the only one who uses Apple.

### Expected Behavior

I expected that for all other players in the server they could use and interact with it. This was also after a lot of relaunching, mod downloading, mod removing and updating, and deep code scanning.

### Version

2.1.4

### Mod Loader Version

1.19.2-43.2.6

### Mod Loader

Forge

### Logs or additional context

I installed optifine and uninstalled it and it wasn't the problem to my knowledge. The other two don't have optifine either. I was, however, the only one with JEI installed and thought that that was the problem, but they now have it installed too and still have the same problem. Another important fact is that the others on the server can open the table but can only see seven options for any block. Blocks that do not have connecting textures such as chiseled deepslate or coded deepslate work just fine.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
We will need to see a crash report in order to help you

**Comment by AlexNijjar** [comment]
Closing as issue is stale
