### ISSUE TITLE
[Bug]: Chipped leaves cannot be waterlogged

### ISSUE THREAD

**Issue by brianfreud** [CookieCNetwork/Chipped#198]
### Bug Description

Normal leaf blocks can be waterlogged.  Chipped leaves cannot.

### How to Reproduce?

Take any leaves block, such as jungle leaves.
Test that it can be waterlogged by clicking on it with a bucket of water.
Success.
Now change it to a to a dead jungle leaves block with the botanist's table.
Try to waterlog it.
Fail to waterlog the block.

### Expected Behavior

Leaves blocks should be able to be waterlogged.

### Version

2.1.4

### Mod Loader Version

1.19.2 - Forge 43.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1.20
<img width="1512" alt="Screenshot 2023-07-05 at 5 29 59 AM" src="https://github.com/terrarium-earth/Chipped/assets/61668546/fa48b427-8763-47ca-a9c7-f399f3816a1a">
