### ISSUE TITLE
[Feature Request]: Find a solution not to use CTM

### ISSUE THREAD

**Issue by NeauChar** [CookieCNetwork/Chipped#199]
### Is your feature request related to a problem?

Find a solution not to use CTM. When using CTM and Rubidium there are a lot of problems with compatibility of mods, long loads and other things.

### Mod Version

2.1.4

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
we're using our own ctm mod on 1.19.4 that fixes all those issues

https://modrinth.com/mod/stitch
