### ISSUE TITLE
Crash on server with the latest version

### ISSUE THREAD

**Issue by starmun-0010** [CookieCNetwork/Chipped#20]
MC: 1.6.5
Forge: 36.1.17
Chipped: 1.1

**To Reproduce**

1. Setup Forge Server
2.  Install Chipped
3.  Run the server

**Crash Report attached below**

[crash-2021-05-14_01.44.56-fml.txt](https://github.com/CookieCNetwork/Chipped/files/6476011/crash-2021-05-14_01.44.56-fml.txt)

**Comment by InfornoFire** [comment]
You are using the new mappings from 1.16.5, use 1.16.4 or an older version of forge 1.16.5 (below 36.1)

**Comment by starmun-0010** [comment]
Lots of major mods require forge >36.1 so it would be good if you guys can update your mod to support it.
There goes my dream of including chipped in my modpack :(
Most major modpacks like ATM6 and Enigmatica 6 also depend on forge >36.1...

![image](https://user-images.githubusercontent.com/5557278/118211533-b4afc400-b485-11eb-858f-5c11ef20f029.png)

**Comment by InfornoFire** [comment]
@grimbop please reopen

**Comment by Darkere** [comment]
Server has no FMLClientSetupEvent. Make sure to only register this for clients. (DistExecutor.safeRunWhenOn(Dist.CLIENT, () -> "register event");) or something similar.

**Comment by terrariumearth** [comment]
we have updated to new mappings, download 1.0.2> to fix <3

**Comment by Darkere** [comment]
This does not fix the issue. It does not matter to the game what type of mappings you are using in your development environment. 

Please try running in server configuration.

**Comment by starmun-0010** [comment]
The problem still persists with 1.0.2.
As Darkere said above, the problem is the com.grimbo.chipped.block.ChippedBlocks.clientRender method registering the FMLClientSetupEvent, which is not available on the server.

Latest crash report is attached below.
[crash-2021-05-16_21.09.44-fml.txt](https://github.com/CookieCNetwork/Chipped/files/6490037/crash-2021-05-16_21.09.44-fml.txt)

**Comment by InfornoFire** [comment]
woops I forgot about this issue

**Comment by InfornoFire** [comment]
Fixed
https://github.com/CookieCNetwork/Chipped/commit/808d3de389b0fd602d692eeab129629fcf08819a
