### ISSUE TITLE
world edit blocks disappear [Bug]: 

### ISSUE THREAD

**Issue by tordyman** [CookieCNetwork/Chipped#200]
### Bug Description

blocks disappear when i use world edit to set chipped blocks

### Version

2.1.4

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Probably an issue on their side? I don't see how chipped can cause this, we don't do anything special with the blocks.
