### ISSUE TITLE
[Bug]: Connected plank textures missing

### ISSUE THREAD

**Issue by kirajelly** [CookieCNetwork/Chipped#206]
### Bug Description

Connected plank textures have vanilla plank textures in the corners. The blocks in item form also use vanilla textures.

![2023-04-28_20 08 12](https://github.com/terrarium-earth/Chipped/assets/128894409/74469cba-bb9d-4048-8907-6b6fac2a4dbb)

### How to Reproduce?

[latest.log](https://github.com/terrarium-earth/Chipped/files/11521396/latest.log)

### Expected Behavior

Connected textures go around the corners, blocks in item form look like the actual block.

### Version

2.1.4

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1.20 version
