### ISSUE TITLE
[Bug]: Vined, overgrown, and leafy trapdoors have gray leaf textures

### ISSUE THREAD

**Issue by kirajelly** [CookieCNetwork/Chipped#207]
### Bug Description

![2023-05-19_19 17 01](https://github.com/terrarium-earth/Chipped/assets/128894409/b53050e3-218e-4d5e-9766-0365f5486807)

### How to Reproduce?

[latest.log](https://github.com/terrarium-earth/Chipped/files/11521401/latest.log)

### Expected Behavior

Leafy + etc. trapdoors are the colors of the leaves of the tree type in the biome.

### Version

2.1.4

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1.20 version
