### ISSUE TITLE
[Feature Request]: Cactus placement on sand varients in the 1.18.2 version

### ISSUE THREAD

**Issue by Anzacer** [CookieCNetwork/Chipped#208]
### Is your feature request related to a problem?

Cactus is unable to be placed on the different variants of sand from the chipped mod, this feature would be very appreciated! 

### Mod Version

2.0.0

### Mod Loader Version

1.18.2 - 40.2.1

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
1.18.2 is no longer supported.
