### ISSUE TITLE
'All rights reserved' on curseforge

### ISSUE THREAD

**Issue by lincore81** [CookieCNetwork/Chipped#21]
Thanks for making this mod CC0! 
I was getting a bit worried because on your curseforge page it says 'All rights reserved'.

**Comment by terrariumearth** [comment]
heya! thats there just as default to say that people can't take our textures and models and such. on the curse page i state at the bottom "You are free to use this mod in your modpacks! Please just provide credit (:", is that what you were worried about?

**Comment by lincore81** [comment]
Hi and thanks for the info. I don't like closed source mods much, because I think the community strongly benefits form open source. So whenever a new mod is released as open source is rejoice :) 

What I don't understand is: If you want credit for your work, then why did you choose CC0 for this project? ./LICENSE applies to everything in this repo, so did you consider using a less permissive license (e. g. CC-BY-SA) for your textures? 

I get that you can't really enforce the terms so you may just as well not have any. Personally, though. I prefer a license that clearly states what the authors want me and don't want me to do with their creation. Kindly asking for credit sounds more like it's ok if I don't and even if it is not meant that way, I assume that your request on curseforge would be overruled by your own license. If I reupload your textures on curseforge I guess due to your license terms there you could shoot my project down. But if I just clone this repo and upload the mod to another site, I think that's fine because it's CC0.

Sorry for the wall of text, I seem to strongly care about licensing terms :)

**Comment by terrariumearth** [comment]
I will look more into this! Thank you for your concerns (:
