### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Orion2852** [CookieCNetwork/Chipped#210]
### Bug Description

When a block is placed next to an upright structure made of a simple, smooth stone pillar, the connections are broken.

### Version

2.1.4

### Mod Loader Version

1.19.2 43.2.11

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
you probably have rubidium which breaks that. in 1.20 and onwards, we'll be using [Athena](https://modrinth.com/mod/athena-ctm) instead of CTM which is compatible with rubidium.
