### ISSUE TITLE
[Bug]: Requires Athena Badge Wrong Link

### ISSUE THREAD

**Issue by Simiea** [CookieCNetwork/Chipped#212]
### Bug Description

Just the wrong link is in the markdown of the "Requires Athena" badge on the Modrinth page. Sends it to an old project by Terrarium called stitch I believe. Should be easy to fix

### How to Reproduce?

Click Requires Athena badge on modrinth page

### Expected Behavior

Sends you to a project Called "stitch" which does not exist anymore

### Version

N/A

### Mod Loader Version

N/A

### Mod Loader

N/A

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported

**Comment by AlexNijjar** [comment]
oops, has been fixed.
