### ISSUE TITLE
[Bug]: Chipped Bookshelves don't have Enchanting Power

### ISSUE THREAD

**Issue by katubug** [CookieCNetwork/Chipped#213]
### Bug Description

The decorative bookshelf variants that Chipped adds do not count towards an Enchanting Table's level.

### How to Reproduce?

1. Place down Chipped bookshelves
2. Access Enchanting Table interfact

### Expected Behavior

I expected that each bookshelf would have enchanting power of 1.

### Version

2.1.5

### Mod Loader Version

1.19.2 - 43.2.11

### Mod Loader

Forge

### Logs or additional context

Sorry, I didn't know whether this was a bug or a feature request, but it seems unintended so here I am! Thanks in advance for your time!

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
This'll be fixed in 1.20 as Mojang added a tag called "enchantment_power_provider" so Chipped's bookshelves will be added to that.

**Comment by katubug** [comment]
Thank you! I'm guessing no plan to fix this in older versions?
