### ISSUE TITLE
Glitched Textures/Animation - Multiple Lanterns [Bug]: 

### ISSUE THREAD

**Issue by doorhandlee** [CookieCNetwork/Chipped#219]
### Bug Description

Glitching textures- parts of lanterns will appear transparent or have missing parts:
- All paper soul lanterns
- Blue tube soul lantern
- Wooden cage soul lantern
- Checkered iron soul lantern

Missing animation- fire is not animated and instead appears as three floating fires:
- Iron bowl soul lantern

[Image Attached]
![2023-07-15_16 49 57](https://github.com/terrarium-earth/Chipped/assets/139640909/d7892ad1-f67e-4069-83c9-1d114bc98626)

### How to Reproduce?

Placing on a block or placing on the underside of a block

### Version

3.0.1

### Mod Loader Version

1.201

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 3.0.2
