### ISSUE TITLE
[Bug]: See through world with deepslate 1.18.2

### ISSUE THREAD

**Issue by TimelessLich** [CookieCNetwork/Chipped#220]
### Bug Description

when looking at deepslate block from chipped you can see through the world in the coners

### How to Reproduce?

1. place mason's workbench 
2. change a Deepslate to Overlapping Deepslate Tiles
3. place Overlapping Deepslate Tiles
4. look at the block with your crosshair

### Expected Behavior

now you should be able to look through the world

### Version

2.0.1

### Mod Loader Version

0.14.14

### Mod Loader

Fabric

### Logs or additional context

currently playing create astral when this happened the version of the modpack is 2.0.4c

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [x] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
"I have verified that I am using the latest version of the mod"
did you test it on 3.0.1? this should be fixed in Chipped 3.0.0 as we switched from CTM to Athena which fixes pretty much all of those rendering bugs

**Comment by TimelessLich** [comment]
> "have verified that I am using the latest version of the mod" did you test it on 3.0.1? this should be fixed in Chipped 3.0.0 as we switched from CTM to Athena which fixes pretty much all of those rendering bugs

3.0.1 does not exist for minecraft version 1.18.2

**Comment by CodexAdrian** [comment]
We are currently not supporting 1.18.2
