### ISSUE TITLE
[Bug]: Door names don't seem to match the blocks

### ISSUE THREAD

**Issue by AndyCat1811** [CookieCNetwork/Chipped#221]
### Bug Description

These door name definitely don't seem to match the actual textures, as if they were mixed up and matched to a random name (not only these doors, they all seem to be affected).  The oak doors look fine but the other wood types all seem to have names that don't match

![2023-07-18_17 48 20](https://github.com/terrarium-earth/Chipped/assets/127636013/76fc301d-6d06-4651-9e64-4e13b8428314)
![2023-07-18_17 48 23](https://github.com/terrarium-earth/Chipped/assets/127636013/14792ffd-e03a-47b6-aad8-a52d78136879)
![2023-07-18_17 48 28](https://github.com/terrarium-earth/Chipped/assets/127636013/a512bb83-14cd-436d-94ab-4e70c8846c6b)
![2023-07-18_17 48 30](https://github.com/terrarium-earth/Chipped/assets/127636013/a225cc64-f46d-4103-9b69-3752fb968404)

### How to Reproduce?

1. Go to the creative inventory.
2. Hover over the door items and see the names.

### Version

2.0.1

### Mod Loader Version

1.18.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AndyCat1811** [comment]
Another one in the same vein : white and yellow checkered terracotta, which I assume should be named "Checkered White Terracotta" and "Checkered Yellow Terracotta" are named "Checkewhite White Terracotta" and "Checkeyellow Yellow Terracotta"

**Comment by AlexNijjar** [comment]
1.18.2 is no longer supported. this should be fixed in the latest version.
