### ISSUE TITLE
[Bug]: Modloading error on server. (Not always, but sometimes)

### ISSUE THREAD

**Issue by Gbergz** [CookieCNetwork/Chipped#222]
### Bug Description

Sometimes when server boots, not always. It results in a modloading error.

### How to Reproduce?

1. Boot Server
2. Wait
3. Modloading error. "Crash."
Profit.

### Expected Behavior

No modloading error, like ever.

### Version

3.0.1

### Mod Loader Version

47.1.3

### Mod Loader

Forge

### Logs or additional context

https://gist.github.com/Gbergz/9968aba1e77c9537fc5290c1cac58c96

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Update resourceful lib
