### ISSUE TITLE
[Bug]: Gridless Etched blocks not available in the latest fabric version

### ISSUE THREAD

**Issue by ParthChavan1311** [CookieCNetwork/Chipped#223]
### Bug Description

The GRIDLESS etched versions of the chipped blocks are not available (ex. Gridless Ethched Bricks Bricks )

### Version

2.1.5

### Mod Loader Version

1.19.2 - 2.1.5

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
they were readded in 1.20. 1.19.2 is no longer supported.

**Comment by ParthChavan1311** [comment]
> they were readded in 1.20. 1.19.2 is no longer supported.

But i remember playing it with the create mod 1.19.2 and they existed 
Not sure why i can't find it now

**Comment by AlexNijjar** [comment]
there was never a 1.19.2 version with gridless bricks. they were originally in 1.18.2 and then removed in 1.19.2 as they seemed kinda redundant but then readded in 1.20.1 due to multiple people wanting them back
