### ISSUE TITLE
[Bug]: needs language providier 47 instead of 46 even though i have the latest forge dowloader for 1.20

### ISSUE THREAD

**Issue by xXLightdustXx** [CookieCNetwork/Chipped#224]
### Bug Description

So ive dowloaded chipped version that supports both forge 1.20 and 1.20.1 but i always have an issue being that when i start the launcher it always goes to that the mod needs language provider 47 instead of 46 when the reality is i have the latest forge dowloaded being 1.20-46.0.14.

### How to Reproduce?

1: have the latest forge dowloader 
2: have the lates mod of chipped for 1.20
3 play the game
4:get the msg of it needing a language provider

### Version

1.20/1.21

### Mod Loader Version

1.20.1-3.0.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
you need forge 1.20.1 every mod should be compatible with 1.20.1

**Comment by xXLightdustXx** [comment]
but it says that its compatible with forge 1.20 tho??

**Comment by AlexNijjar** [comment]
just use 47.1.3

**Comment by xXLightdustXx** [comment]
> you need forge 1.20.1 every mod should be compatible with 1.20.1

but it says its compatible with 1.20 too
