### ISSUE TITLE
[Feature Request]: Split Creative Inventory Tab into multiple tabs

### ISSUE THREAD

**Issue by ParanormalChicken** [CookieCNetwork/Chipped#225]
### Is your feature request related to a problem?

I personally find the current creative inventory tab hard to navigate through, and it's quite overwhelming at times.

### Solution(s)

It could be split into multiple tabs, e.g. Chipped Metals and Gems, Chipped Stones, Chipped Wood, etc.

### Mod Version

3.0.1

### Mod Loader Version

1.19.2 & 1.20.1

### Mod Loader

Quilt

**Comment by AlexNijjar** [comment]
Even if it's split, there are **10,000** block in chipped. I don't think that'll make it easier to read. You should really just use JEI for viewing chipped blocks.
