### ISSUE TITLE
[Bug]: blocks not rendering

### ISSUE THREAD

**Issue by enchantedgaple** [CookieCNetwork/Chipped#226]
### Bug Description

when I try and place some blocks particularly the striped concrete it doesn't render them even if I relog and this is for every one of these blocks I place and I have checked if this is a shader or recourse pack bug but it didn't seem to change anything, it might be a mod conflict but I only have 1 other mod that adds 1 block 

![2023-08-13_11 22 08](https://github.com/terrarium-earth/Chipped/assets/142171714/55db4d22-3a1f-40e2-8b6b-61ddaab17ebb)

### How to Reproduce?

1. get a striped concrete block
2. place it 

### Expected Behavior

it should render the block

### Version

1.20.1

### Mod Loader Version

3.0.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
you likely have sodium but not indium

**Comment by enchantedgaple** [comment]
> you likely have sodium but not indium

thanks I think that was the issue
