### ISSUE TITLE
[Bug]: Placing a Chipped block on a server changes it for a different block

### ISSUE THREAD

**Issue by Tempest-5ky** [CookieCNetwork/Chipped#227]
### Bug Description

More or less what it says on the tin! Placing any Chipped block (we've tried Chipped 2.1.5 and 2.1.4 with the same results) results in a different block on our modded server. This only occurs on the server, not in singleplayer. No errors in logs.

### How to Reproduce?

1. Put chipped on the server and client
2. Join server
3. Try to place block

### Expected Behavior

Blocks remain what you expect them to be

### Version

2.1.5

### Mod Loader Version

1.19.2 - Fabric 0.14.21

### Mod Loader

Fabric

### Logs or additional context

https://github.com/terrarium-earth/Chipped/assets/99220350/b0f9d82e-2b82-4da9-9666-6147846f8bc2

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
are you sure the client version is the same as the server version?

**Comment by Tempest-5ky** [comment]
Yep! Exact same file, even.

**Comment by AlexNijjar** [comment]
This is almost certainly not an issue with chipped. You most likely have some other mod that's messing with the block registration order. Try with only chipped installed

**Comment by ThatGravyBoat** [comment]
Closing as no more comments on the issue was given.
