### ISSUE TITLE
[Bug]: Crash at Loading Screen

### ISSUE THREAD

**Issue by ApogeeKaiten** [CookieCNetwork/Chipped#229]
### Bug Description

After activating each mod on my modlist, I singled out that it's Chipped.

Here is my Crash Report with the modlist: 
https://mclo.gs/cGHkjM3

### Version

3.0.1

### Mod Loader Version

1.20.1 - 47.1.44

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
not a single thing in there points to chipped everything in there points to iris/oculus

**Comment by ApogeeKaiten** [comment]
When I disable chipped from the modlist, everything seems to work properly. Funnily enough, when i tried out an older version of the modpack with both oculus and chipped instaled, everything seemed to work fine. Same versions of both mods. 

Edit: Are there any mods that don't gel well with both Chipped and Oculus combined?
