### ISSUE TITLE
Improve Workbenches Hitboxes

### ISSUE THREAD

**Issue by InfornoFire** [CookieCNetwork/Chipped#23]

**Comment by AudreyOooo** [comment]
Make 2 block tall benches 2 blocks tall

**Comment by InfornoFire** [comment]
Minecraft lets you do voxel shapes thingies that let blocks occupy a 2 x 2 space but have better dimensions that resemble the model. This should really only be a problem with the one workbench that has the furnace on it

**Comment by AlexNijjar** [comment]
Fixed in d1cb335
