### ISSUE TITLE
[Feature Request]: maybe a typo of coarse 

### ISSUE THREAD

**Issue by Catcatpigeon** [CookieCNetwork/Chipped#232]
### Is your feature request related to a problem?

![1693905357278](https://github.com/terrarium-earth/Chipped/assets/136223541/8a914718-0bdd-4615-80b3-4b6123f33e7d)
Thank you for making this mod. I am now doing some translation work on this mod, I wonder if this is actually 【coarse sand】?

### Mod Version

3.0.1

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by Catcatpigeon** [comment]
a question about the ring lodestone. One with【sides】, TTTTT But I can't find any difference between these two blocks.
![1693908175851](https://github.com/terrarium-earth/Chipped/assets/136223541/e6637811-7906-4b2a-954f-a31540f1b1b4)
![1693908197163](https://github.com/terrarium-earth/Chipped/assets/136223541/59c1b232-002b-4db2-8758-0a1d81dd653e)
![1693908342234](https://github.com/terrarium-earth/Chipped/assets/136223541/fa81068f-be69-46b5-8090-4986ab06e69a)
also, the blocks like XXX Glazed Terracotta Pillar 【Sides】, what does the 【sides】mean here? 
![1693908928481](https://github.com/terrarium-earth/Chipped/assets/136223541/d7a7440f-330f-4bf8-9f07-f23ec01bb2d4)

**Comment by AlexNijjar** [comment]
Oh my, you poor soul. You do realize the en_us file is 7,000 lines long, right?

- yeah, it's a typo.
- some of the blocks were missing textures so their textures were temporary duplicated. that one might have not been changed yet.
- I think it's called that because it's meant to like like the side of a pillar?

**Comment by Catcatpigeon** [comment]
thank you for answering me~ I got it!
