### ISSUE TITLE
[Bug]: (Fabric) Blocks with connected textures not rendering when using Sodium

### ISSUE THREAD

**Issue by theflydeluxe** [CookieCNetwork/Chipped#233]
### Bug Description

When using Chipped (Fabric version, with Athena and Resourcefullib) with Sodium mod blocks with connected textures (Arched glass panes etc) do not render at all when placed. 

### Version

3.0.1

### Mod Loader Version

Fabric 0.11.2

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
you need indium as well
