### ISSUE TITLE
[Feature Request]: EMI Support

### ISSUE THREAD

**Issue by HeraldOD** [CookieCNetwork/Chipped#235]
### Is your feature request related to a problem?

Chipped recipes are not displayed in EMI like they are with REI or JEI.

### Solution(s)

When viewing Chipped blocks in EMI, one should be able to see the recipes.

### Mod Version

2.1.5

### Mod Loader Version

1.19.2 - 0.14.22

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
EMI hooks into JEI’s API. you need to have both installed

**Comment by HeraldOD** [comment]
Oh, I wasn't aware, thanks for the info!
