### ISSUE TITLE
[Feature Request]: 1.19.4 version

### ISSUE THREAD

**Issue by Ratnukii** [CookieCNetwork/Chipped#236]
### Is your feature request related to a problem?

Incompatibility with 1.19.4

### Solution(s)

it would be great if this mod could be ported to 1.19.4 for mods that havent been updated to 1.20 but are post 1.19.2/3

### Describe alternatives you've considered

Attempted looking for replacement mods but Chipped is just the only one that does what it needs to do the right way!

### Mod Version

2.1.5

### Mod Loader Version

1.19.4

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
1.19.3 and 1.19.4 are dead versions. By now most people have updated to 1.20.1 so I don't think it's worth the effort.
