### ISSUE TITLE
[Bug]: Philosopher's Workbench missing in Chipped 1.19.2 2.1.5

### ISSUE THREAD

**Issue by FoxySophie** [CookieCNetwork/Chipped#237]
### Bug Description

I noticed that the Philosopher's Workbench is completely missing, there isn't even an entry in REI for it, which makes it impossible to craft any of the glowstone, amethyst etc variants.

### Version

2.1.5

### Mod Loader Version

1.19.2 - 0.14.22

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by azul3ra** [comment]
I unfortunately am having this same issue

**Comment by AlexNijjar** [comment]
it was renamed to the alchemy bench

**Comment by FoxySophie** [comment]
Okay, that's good to know, but the name in the UI and recipes is still wrong then, cause it still shows "Philosopher's Workbench", that's why we couldn't find it, see images attached.

<img width="652" alt="javaw_uD5EZ4EaNP" src="https://github.com/terrarium-earth/Chipped/assets/2241179/7ffc413d-904a-4879-bd61-619546503b43">
<img width="369" alt="ShareX_IgQH9zf2pJ" src="https://github.com/terrarium-earth/Chipped/assets/2241179/cbef5409-86f2-4330-8cd1-33090ce10986">

**Comment by AlexNijjar** [comment]
It's been fixed and will be in the next update
