### ISSUE TITLE
[Bug]: Chipped Workbenches not working for all blockvariations

### ISSUE THREAD

**Issue by VengefulNick** [CookieCNetwork/Chipped#239]
### Bug Description

We've encounterd an issue on our server lately when using the workbenches from chipped to get block variations of said block.

The bug does not affect a specific workbench (carpenter,mason,botanist, etc) its just random blocks that somehow does not get its corresponding variations through the benches.

![stone_chipped_functional](https://github.com/terrarium-earth/Chipped/assets/89831583/29c73362-0684-49da-a408-87a9bd382a42)

![bricks_chipped_not_functional](https://github.com/terrarium-earth/Chipped/assets/89831583/0ef463d7-b40f-47ff-9d13-25e52a16d310)

![dirt_chipped_not_functional](https://github.com/terrarium-earth/Chipped/assets/89831583/0570ceec-f3a4-4275-80bf-0040d56ceb08)

![carpets_chipped_not_functional](https://github.com/terrarium-earth/Chipped/assets/89831583/afef81ce-748f-47b0-807e-febc32eb444d)

Also the affected blocks does not show how to craft them through JEI when clicking to show recipe.

Blocks placed in the world previously of now non working variations are still both showing and obtainable through gathering of em.

### How to Reproduce?

1. Place workbench
2. Put block into the input slot
3. View the variations in the output window ( which does not occur for the affected blocks)

### Expected Behavior

Get the output options for every block in chipped to actually show in the GUI

### Version

1.19.2-2.1.5

### Mod Loader Version

43.2.14

### Mod Loader

Forge

### Logs or additional context

Modpack used: https://www.curseforge.com/minecraft/modpacks/uberswes-community-server

Modlist:
![modlist_uber](https://github.com/terrarium-earth/Chipped/assets/89831583/ab7a476e-1da9-4653-90c1-92a43a6b377f)

Note: These are clientside mods used. Server does not have the client-side only mods

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by xLufi** [comment]
I am having this issue as well on my server. Blocks will randomly disappear from the workbenches and their recipes will not show in REI. Restarting the server will fix the issue, but then later on different blocks will be missing again. Placed blocks are not affected, only recipes. I haven't changed any chipped items in Kubejs, but I do have custom recipes for other items. 

Version
1.20.1-3.0.1

Mod Loader Version
0.14.22

Mod Loader
Fabric

![image](https://github.com/terrarium-earth/Chipped/assets/73973485/f70048e7-a41c-4942-8ad1-b168468a290b)

**Comment by Ninsly** [comment]
I also have this issue on my AllTheMods 9 server (v0.2.6).
I discovered that running the JEI admin command `/reload` will fix the issue for that session.

**Comment by VengefulNick** [comment]
We tried to do a reload on the server side and it seems to have helped for the time being!
