### ISSUE TITLE
Ability to rotate clock texture. 

### ISSUE THREAD

**Issue by jlwinter99** [CookieCNetwork/Chipped#240]
### Is your feature request related to a problem?

A block orientation is always dependent on the cardinal directions of the world.

### Solution(s)

I would be nice if the chipped blocks orientation was dependent on the players facing direction like a dropper or dispenser.

### Mod Version

3.0.1

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Additional context

Thank you to whoever addresses this.

**Comment by CodexAdrian** [comment]
This would not be feasible
