### ISSUE TITLE
[Feature Request]: Rotation in all 6 directions

### ISSUE THREAD

**Issue by Mr-Ashton** [CookieCNetwork/Chipped#242]
### Is your feature request related to a problem?

Blocks like logs that can normally be rotated in 6 directions can only be rotated in 3. It would be nice, for example I could have the stripped part of these logs to be touching.
![Screenshot 2023-10-24 131406](https://github.com/terrarium-earth/Chipped/assets/148897613/1b2caebe-cdae-4aa3-bad7-4707b069f517)

### Mod Version

1.20.1

### Mod Loader Version

47.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
We're really trying to cut down on blockstates here. Adding more rotations would increase the number of blockstates.
