### ISSUE TITLE
[Feature Request]: Biomes O' Plenty compatibility

### ISSUE THREAD

**Issue by ArsiTheFox** [CookieCNetwork/Chipped#243]
### Mod Version

Chipped-forge-1.20.1-3.0.1

### Mod Loader Version

Forge: 47.2.1

### Mod Loader

Forge

### Additional context

Can we have Biomes O' Plenty compatibility to be able to put the different wood types or other blocks in the benches

**Comment by AlexNijjar** [comment]
We have no interest in adding mod compat for the foreseeable future.
