### ISSUE TITLE
[Bug]: Mod requiring client-side mod in server

### ISSUE THREAD

**Issue by GameBurrow** [CookieCNetwork/Chipped#245]
### Bug Description

Upon adding Chipped mod to server, server fails to launch, requiring Athen, which is marked as client-side only mod by default on modrinth.

### Version

3.0.1

### Mod Loader Version

0.14.24

### Mod Loader

Fabric

### Logs or additional context

```
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    | [09:06:35] [main/INFO]: Fix: add [add:athena 3.0.0 ([[3.0.0,∞)])], remove [], replace []
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    | [09:06:36] [main/ERROR]: Incompatible mods found!
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    | net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    | A potential solution has been determined, this may resolve your problem:
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    |          - Install athena, version 3.0.0 or later.
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    | More details:
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    |          - Mod 'Chipped' (chipped) 3.0.1 requires version 3.0.0 or later of athena, which is missing!
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    |         at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.24.jar:?]
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    |         at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) ~[fabric-loader-0.14.24.jar:?]
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    |         at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.14.24.jar:?]
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    |         at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.24.jar:?]
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    |         at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    |         at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    |         at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
transportcraft-lite_server.1.rn6lzsagv0cs@sepaurg-servers1    | 2023-11-07T09:06:36.028Z        WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.
```

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Fabric does not have away of making a dependency as client only, Athena does not do anything on the server you can just shove it in there

**Comment by Hex4dec** [comment]
Modrinth does. Packwiz respects that, so Athena should be listed as being compatible but not required on the server on Modrinth.

**Comment by ThatGravyBoat** [comment]
fabric does not respect it so until fabric respects it it will be required

**Comment by ThatGravyBoat** [comment]
https://github.com/FabricMC/fabric-loader/issues/464#issuecomment-1865096055 reference to the fabric issue

**Comment by Hex4dec** [comment]
> fabric does not respect it so until fabric respects it it will be required

You shouldn't be shipping broken metadata in the hope that it will work some day. You need to make sacrificies that aren't exactly in-line with your program's ideology (or your own ideology on programming), and that's fine.

**Comment by CodexAdrian** [comment]
Changing the metadata would mean that Chipped jars on the client will not throw an error if Athena isn't present. I'm not sure what you're going on about sacrificing, but doing that would be problematic for that reason. When fabric fixes this we will change it, thats it
