### ISSUE TITLE
[Bug]: Invisable Blocks

### ISSUE THREAD

**Issue by Avitalll** [CookieCNetwork/Chipped#248]
### Bug Description

Im creating a small modpack for a friend to learn minecraft for the first time. Only consist of 15 mods. Including chipped and its dependencies. But I have Sodium installed as well. But some blocks show up fine, while others are down right invisable.

### How to Reproduce?

1. Place a block like normal
2. Some blocks show up fine while others don't.

### Expected Behavior

Blocks not being invisable.

### Version

chipped-fabric-1.20.1-3.0.1.jar

### Mod Loader Version

chipped-fabric-1.20.1-3.0.1.jar

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Avitalll** [comment]
![image](https://github.com/terrarium-earth/Chipped/assets/150331728/01f2f1f8-15dc-4386-8967-c8ed774e8bbb)

**Comment by ThatGravyBoat** [comment]
If you are using sodium make sure indium is installed

**Comment by ThatGravyBoat** [comment]
Gonna close for now if you are using indium please make another issue report with your whole mod list
