### ISSUE TITLE
[Feature Request/bug?]: Translation file is one ginormeous line of code

### ISSUE THREAD

**Issue by Bloodaxe95** [CookieCNetwork/Chipped#256]
### Is your feature request related to a problem?

The file en_us.json seems to be one gigantic line in stead of neatly sorted elements. This makes the file extremely slow to open in editing software, as well as cumbersome to do translations for the mod. It's pretty much impossible to do translations whilst this remains as it is.

### Solution(s)

Look at how other mod-authors have made their translation-files, and copy their method. Separating each object on it's own line to make it easier to understand and navigate.

### Mod Version

3.0.1

### Mod Loader Version

1.20.1 - 0.15.1

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
it was separated, we just use a json minimizer to put all json files on 1 line to make the final jar smaller. most editors have json beautifiers. use that.

**Comment by Bloodaxe95** [comment]
Aah, I see! I had no idea that affected performance in any way, cool stuff :smile: I will use a json beautifier and try to do some translation.
