### ISSUE TITLE
[Crash]: Athena missing on server , pls remove the need for servers

### ISSUE THREAD

**Issue by xR4YM0ND** [CookieCNetwork/Chipped#257]
### Bug Description

Athena is fully client side, but it needs to be on the server if chipped is installed.

Pls remove the need cause Athena won't get tagged as server side.

https://github.com/terrarium-earth/Athena/issues/11

### Version

3.0.1

### Mod Loader Version

0.15.3

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
This is a problem with fabric not supporting client only dependencies, you can see a request for such feature here on the fabric loader repo https://github.com/FabricMC/fabric-loader/issues/464
