### ISSUE TITLE
Corruption

### ISSUE THREAD

**Issue by BobBobson8** [CookieCNetwork/Chipped#258]
### Bug Description

When uninstalling Chipped and its dependencies (because it was too laggy), I boot up Minecraft again to FIND THE WORLDS I PLAYED WITH CHIPPED ARE CORRUPTED.

### How to Reproduce?

1. install chipped with dependencies
2. play a world
3. uninstall chipped as well as its dependencies
4. open up Minecraft and go back to that same world,
5. find your worlds corrupted with no way of getting them back :(

### Version

3.0.1

### Mod Loader Version

1.20.1-47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
That is just the nature of modded Minecraft, removing a mod from a world can cause corruption and is why everyone suggests regular backups of important worlds. We do not do anything special in chipped and just register blocks so if your world got corrupted there is nothing we can do. You can use the backup button in Minecraft itself by clicking on the world and then edit then make backup, you can also click open backups folder to see if you already have any. Sorry again but nothing we can do that is just how Minecraft data works when you add or remove registries in mass.
