### ISSUE TITLE
[Bug]: Ladders and lily pads have default textures

### ISSUE THREAD

**Issue by Knopfi02** [CookieCNetwork/Chipped#267]
### Bug Description

All ladder and lily pad variants have the default textures. (With the lily pads being grey)

![2024-01-25_01 57 42](https://github.com/terrarium-earth/Chipped/assets/65189138/226e0a89-7abd-4222-8b93-0609bddf806d)

![2024-01-25_02 02 38](https://github.com/terrarium-earth/Chipped/assets/65189138/9c9b277e-6cbf-4632-83e7-61da9d4ce05b)

### How to Reproduce?

1. Place the respective blocks
2. Look at the blocks

### Expected Behavior

Have the correct textures.

### Version

3.0.1

### Mod Loader Version

1.20.1 - 47.1.0

### Mod Loader

Forge

### Logs or additional context

Full list of mods used:

- AdvancementPlaques-1.20.1-forge-1.4.10.jar
- appleskin-forge-mc1.20.1-2.5.0.jar
- athena-forge-1.20.1-3.0.0.jar
- Axiom-1.4.0-for-MC1.20.1.jar
- BigShot-forge-1.20.1-1.0.1.jar
- create-1.20.1-0.5.1.d.jar
- istantHorizons-2.0.0-a-1.20.1.jar
- dynamiclightsreforged-1.20.1_v1.5.0.jar
- FarmersDelight-1.20.1-1.2.4.jar
- Fastload-Reforged-mc1.20.1-3.4.0.jar
- FastSuite-1.20.1-5.0.1.jar
- ferritecore-6.0.0-forge.jar
- Forgematica-0.1.2-mc1.20.1.jar
- freecam-forge-1.2.1+1.20.jar
- handcrafted-forge-1.20.1-3.0.5.jar
- Iceberg-1.20.1-forge-1.1.13.jar
- InventoryProfilesNext-forge-1.20-1.10.9.jar
- Jade-1.20.1-forge-11.5.1.jar
- jei-1.20.1-forge-15.2.0.27.jar
- journeymap-1.20.1-5.9.18-forge.jar
- kotlinforforge-4.8.0-all.jar
- libIPN-forge-1.20-4.0.1.jar
- lighty-forge-2.1.2+1.20.1.jar
- MaFgLib-0.1.3-mc1.20.1.jar
- moonlight-1.20-2.8.6-forge.jar
- MouseTweaks-forge-mc1.20-2.25.jar
- notenoughcrashes-4.4.7+1.20.1-forge.jar
- Placebo-1.20.1-8.3.5.jar
- polymorph-forge-0.49.2+1.20.1.jar
- resourcefullib-forge-1.20.1-2.1.9.jar
- rubidium_extras-1.20.1_v1.4.3.jar
- rubidium-0.6.5.jar
- spark-1.10.53-forge.jar
- supplementaries-1.20-2.5.26.jar

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Can't seem to reproduce it
<img width="1512" alt="Screenshot 2024-02-10 at 4 51 54 PM" src="https://github.com/terrarium-earth/Chipped/assets/61668546/fcbb25e4-cecb-4e90-8ae1-6e8e73701c39">

**Comment by Knopfi02** [comment]
Hmmm, I would ask, if it also happens when you have all the other mods installed, but that'd probably be wayy to much effort 
(unless you did that, in which case, I'd be even more confused as to why it's not working)

**Comment by AlexNijjar** [comment]
Yeah, I only tested with chipped and athena. You can try updating to 3.0.4 but I doubt that'll fix it, most likely another mod breaking it

**Comment by Knopfi02** [comment]
hmm yeah, I might try to go through and find out which mod causes the issue, but thanks for testing it :)

**Comment by Knopfi02** [comment]
Good news, it was an outdated resourcepack, which I forgor that I had, that overwrote the normal ladder and lilypad textures! :D
