### ISSUE TITLE
[Bug]: Crash on launch, NeoForge

### ISSUE THREAD

**Issue by Abalieno** [CookieCNetwork/Chipped#272]
### Bug Description

I have somewhat similar problems with Chipped, Ad Astra and Tempad, but let's start here.

(image is from yesterday, crash long more up to date)

![ui,oul](https://github.com/terrarium-earth/Chipped/assets/4656436/4227384a-1c11-46b8-89ef-d6d800f79ed3)

### How to Reproduce?

Simple launch.

### Version

Chipped-neoforge-1.20.4-3.1.1

### Mod Loader Version

20.4.151

### Mod Loader

NeoForge

### Logs or additional context

https://gist.github.com/Abalieno/2856e88a3ad13b16322cd3ea930a1006

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This is being fixed soon. If you want a temporary fix, install Architectury API
