### ISSUE TITLE
[Feature Request]: in forge 

### ISSUE THREAD

**Issue by Pokecraft1234** [CookieCNetwork/Chipped#285]
### Is your feature request related to a problem?

Hello ,I would like your mode to be compatible with forge, this is the case except that it requires fabric API which is not available, do you have a solution please?

### Solution(s)

Solution:don’t require fabric API

### Describe alternatives you've considered

Chipped with forge 

### Mod Version

None

### Mod Loader Version

1.20.1

### Additional context

None

**Comment by AlexNijjar** [comment]
https://www.curseforge.com/minecraft/mc-mods/chipped/files/5077656
