### ISSUE TITLE
[Bug]: Game Crash

### ISSUE THREAD

**Issue by cleeky** [CookieCNetwork/Chipped#286]
### Bug Description

Game started via MultiMC 5 - Version 0.7.0-3838
Mod Loader: Forge client 47.2.0
Games starts to load then crash and exit 
Crash Report:  https://pastebin.com/vLRFnfX6

### How to Reproduce?

launch instance fromMMC

### Version

3.0.4

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
This is due to sophisticated backpacks using an outdated version of chipped. Check if there's a new version of sophisticated backpacks that fixes it. If not, either remove chipped or sophisticated backpacks until they release a fix.
