### ISSUE TITLE
[Bug]: incompatible with the Sophisticated backpacks mod. 1.18.2

### ISSUE THREAD

**Issue by TheRealScia** [CookieCNetwork/Chipped#292]
### Bug Description

Ive tried all the 1.18.2 versions and Chipped doesnt seem to be compatible with the Sophisticated backpacks mod.

### Version

1.18.2

### Mod Loader Version

1.18.2 - 40.2.4

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
that's not our issue. I'm not even sure if Sophisticated added compat in 1.18.2
