### ISSUE TITLE
[Bug]: All work tables can craft all blocks?

### ISSUE THREAD

**Issue by Nova-Katt** [CookieCNetwork/Chipped#298]
### Bug Description

Hi, so I'm a bit confused and unsure if it is working as intended or if it's a bug OR if it's a bug introduced by other mods running.
Basically, we have a bunch of different tables. Botanist, Glassblower, Mason, etcetera.
It would make sense that the glass blocks are crafted in the Glassblower, and the stone blocks are crafted with the Mason table, and so on.
But it seems like whichever Chipped table I choose, I can craft all the blocks in it.
I can craft glass variants in the botanist, mason, carpenter table and so on.
As long as I have the block in my inventory and click it, all the options for it is there, whichever table I use.

a: Is this intended? As in, I only really need 1 table, and can then pick the one which art style fits best?
b: Or are they supposed o be separate so you need different ones for different blocks?
c: Or could it be that it's supposed to work like b, and does work like b... BUT another mod makes it work like a?

Just to get some clarity here. :)

### How to Reproduce?

Have blocks in inventory.
Use whichever chipped table to craft it's variants.

### Expected Behavior

Have blocks in inventory.
Use the corresponding chipped table for the corresponding block types. Like glass stuff in the glassblower, and so on.

### Version

1.20.4

### Mod Loader Version

fabric-loader-0.15.10-1.20.4

### Mod Loader

Fabric

### Logs or additional context

Attached screenshot of all the mods I run, incase there are some compat issues you know of that I do not know of. :)
![modlist](https://github.com/terrarium-earth/Chipped/assets/37087535/c7deb9f4-4e7c-4848-b368-5e898a2d4b36)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This is intended behavior

**Comment by Nova-Katt** [comment]
> This is intended behavior

Probably the fastest reply I've ever gotten on a github **ever** :P
Okay, so it was option A, use 1 table and we just have different styles to pick from then. ^_^

**Comment by CodexAdrian** [comment]
Yep. We kept all the tables to use as decoration blocks 😄

**Comment by Nova-Katt** [comment]
Lovely! Work are doesn't take 20 blocks extra, just 2, and we can make it fit the theme of our builds. Excellent, I love it! :D
