### ISSUE TITLE
[Bug]: Images are broken on Modrinth mod page

### ISSUE THREAD

**Issue by lewisfm** [CookieCNetwork/Chipped#307]
### Bug Description

The images on the Modrinth page for Chipped do not load and give 404s.

### How to Reproduce?

1. Go to "https://modrinth.com/mod/chipped"

### Expected Behavior

The images should load so I can see what the mod's blocks look like.

### Version

N/A

### Mod Loader Version

N/A

### Mod Loader

N/A

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by TheCuteCultist** [comment]
Would like to add its the same for curseforge aswell ^^

**Comment by AlexNijjar** [comment]
looks like @CodexAdrian fixed the modrinth page. curseforge page is still broken

**Comment by participle38** [comment]
Curseforge still broken
