### ISSUE TITLE
0%

### ISSUE THREAD

**Issue by zc1108aaa** [CookieCNetwork/Chipped#308]
### Bug Description

![B`7%{5)XUQP6`%A35$HLBS](https://github.com/terrarium-earth/Chipped/assets/155424398/0b9c6009-26d6-44f8-90df-c54bc1491930)

### How to Reproduce?

1

### Expected Behavior

1

### Version

3.0.6

### Mod Loader Version

1.20.1-0.15.11

### Mod Loader

Fabric

### Logs or additional context

[latest.log](https://github.com/user-attachments/files/15710644/latest.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
...? Please actually write a description for your bug

**Comment by zc1108aaa** [comment]
athena-fabric-1.20.1-3.1.1 No problem opening it
athena-fabric-1.20.1-3.1.2 Open card 0%
Is this the problem

**Comment by CodexAdrian** [comment]
You need to provide alot more information. Athena on its own does not behave this way. How did you come to the conclusion that it was Athena that was causing this issue? What other mods do you have present?

**Comment by zc1108aaa** [comment]
I can't open it until I update a few mods
![image](https://github.com/terrarium-earth/Chipped/assets/155424398/59cfef91-99cf-4cfa-9104-9f90c9dec508)
1
![image](https://github.com/terrarium-earth/Chipped/assets/155424398/6c3d1ce9-0fd1-4aad-9136-f8adb6a244a2)
