### ISSUE TITLE
[Feature Request]: Textures

### ISSUE THREAD

**Issue by Gavin456b** [CookieCNetwork/Chipped#311]
### Is your feature request related to a problem?

I think it would be nice if the variants pulled textures from your resource pack so there can be some consistency with the other blocks. Either as a config option or by default. Like other mods do (Macaws, Crayfish, ect...) It seems to be already possible because when using Chipped in conjunction with EveryCompat, Chipped variants for modded blocks are added. 

### Mod Version

1.19.X

### Mod Loader Version

1.19.2 43.4.0

### Mod Loader

Forge

**Comment by CodexAdrian** [comment]
Thats not really how resource packs work, every compat's system is another thing entirely. Dynamic textures for all blocks in chipped is not something we plan on supporting

**Comment by Gavin456b** [comment]
Well I'm not suggesting the resource pack _do_ anything, but if EveryCompat is already doing it then it is possible

That being said if you don't plan to implement it then that's fine.
