### ISSUE TITLE
[Feature Request]: Slabs and stairs

### ISSUE THREAD

**Issue by fifflesniffle** [CookieCNetwork/Chipped#312]
### Is your feature request related to a problem?

Slabs, being half the height of normal blocks, can be used to create depth in builds. In my case, I want to create a ceiling with the shape of the section on the left, with the pattern of the planks on the right.
![image](https://github.com/terrarium-earth/Chipped/assets/41874925/bdc17f83-c726-4c3c-b1cd-340c0a71b63d)

### Solution(s)

The ability to apply the same patterns to slabs and stairs, just like on normal blocks. That way, _every_ block can have a friend.

In the case of my ceiling, I could make birch plank slabs, put them into the carpenter's table, and get any of the patterns that can be applied to normal birch planks on the slabs instead.

### Mod Version

3.1.4

### Mod Loader Version

1.20.4 - 0.15.11

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
Adding slabs and stairs for all of Chipped's thousands of blocks would cause a significant increase in memory usage and startup times. As such this is not something I'd be interested in adding. I'd recommend [Framed Blocks](https://www.curseforge.com/minecraft/mc-mods/framedblocks). However I don't believe there's a fabric alternative for that.
