### ISSUE TITLE
[Bug]: All stations have all recipes

### ISSUE THREAD

**Issue by Ayyavazi** [CookieCNetwork/Chipped#317]
Sorry, didn't check closed issues. It appears this is intended behavior, sorry for the clutter.

### Bug Description

Any station (mason, carpenter, etc.) contains all recipes for all other stations, allowing the working of wood on the alchemy bench, for example, and other crazy combinations.

Good for convenience, but not in the spirit of the mod.

### How to Reproduce?

Install mod
Craft any station
Access station with inappropriate material
Profit?

### Expected Behavior

Mason station only accepts stone based items, carpenter wood based, and so on.

### Version

Current

### Mod Loader Version

1.21 fabric, most recent

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
This is an intended feature
