### ISSUE TITLE
[Bug]: some Blocks is invisible

### ISSUE THREAD

**Issue by ArrafiDinner** [CookieCNetwork/Chipped#329]
### Bug Description

![2024-08-14_20 38 04](https://github.com/user-attachments/assets/fd68f171-1768-477f-be1d-0be92d503617)
House

![2024-08-14_20 42 16](https://github.com/user-attachments/assets/44a3d45b-bb86-4375-b844-6698105ff05e)
 Carpenters tables
 
 
![2024-08-14_20 42 47](https://github.com/user-attachments/assets/45e90547-389f-4c80-923c-4470ed8793e6)
placed

### How to Reproduce?

1. Make the Custom blocks from the Carpenters tables/other.
2. place the Custom blocks
3. invisible

But my friend using same multiple mods, with chipped mod in it, but they have no issues. just me

### Expected Behavior

.

### Version

4.0.0

### Mod Loader Version

1.21

### Mod Loader

Fabric

### Logs or additional context

.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
If you are using sodium you need indium

**Comment by ArrafiDinner** [comment]
> If you are using sodium you need indium

YES, IM BACK HERE TO REPLY THAT I NEED INDIUM.
