### ISSUE TITLE
[Bug]: Crash on 1.21.1 when looking at barrel

### ISSUE THREAD

**Issue by JaisDK** [CookieCNetwork/Chipped#330]
### Bug Description

Reported in ATM10 discord

https://mclo.gs/1d74vRU

### Version

neoforge-1.21-4.0.0

### Mod Loader Version

21.1.8

### Mod Loader

NeoForge

### Logs or additional context

https://mclo.gs/1d74vRU

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by djnifos** [comment]
Here's a log with minimal mods to reproduce 

https://mclo.gs/1Tqxidh

client-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		handcrafted-neoforge-1.21.1-4.0.2.jar             |Handcrafted                   |handcrafted                   |4.0.2               |Manifest: NOSIGNATURE
		resourcefullib-neoforge-1.21-3.0.9.jar            |Resourceful Lib               |resourcefullib                |3.0.9               |Manifest: NOSIGNATURE
		athena-neoforge-1.21-4.0.0.jar                    |Athena                        |athena                        |4.0.0               |Manifest: NOSIGNATURE
		neoforge-21.1.22-universal.jar                    |NeoForge                      |neoforge                      |21.1.22             |Manifest: NOSIGNATURE
		chipped-neoforge-1.21-4.0.0.jar                   |Chipped                       |chipped                       |4.0.0               |Manifest: NOSIGNATURE

**Comment by tylacine** [comment]
I am having this issue with placing any of the barrel types--it's an instant crash.

**Comment by CodexAdrian** [comment]
Fixed in latest, release coming out in a bit
