### ISSUE TITLE
Bits from Chisels and Bits are not showing when Chipped is installed.

### ISSUE THREAD

**Issue by Lorrowin** [CookieCNetwork/Chipped#34]
As the title says, with Chisels and Bits, and Chipped together, the bits from Chisels and Bits mod do not show in creative tab. You can still chisel blocks with the chisel, but you do not get the bits into your inventory, nor can you see or select any in creative. 

I'm not sure what other information would be useful for this issue. :)

The only mods I used were the latest versions of chisels and bits (0.3.4-RELEASE) and Chipped (1.0.4.) on Forge 36.1.0.

**Comment by terrariumearth** [comment]
im pretty sure this is a chisel and bits bug with mods in general, not much I can do about it atm :(
