### ISSUE TITLE
[Bug]: Missing GUI Texture in JEI - 1.20.1

### ISSUE THREAD

**Issue by muggleorwizard** [CookieCNetwork/Chipped#341]
### Bug Description

Install JEI and chipped, view a block recipe. Missing GUI texture. See https://github.com/mezz/JustEnoughItems/issues/3777
From mezz of JEI: "Thanks for the report!
It looks like the other mod was depending on a texture that is used internally by JEI. The texture has been removed from JEI, so their plugin is now broken. Please report this bug to them so that they can fix their GUI texture, and please link back to this issue in case they'd like me to help them."

### Version

1.20.1-3.0.6

### Mod Loader Version

1.20.1-47.3.10

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by muggleorwizard** [comment]
Just following up on this issue - thanks!

**Comment by mezz** [comment]
I created a PR that will fix the issue here: 
* https://github.com/terrarium-earth/Chipped/pull/344

**Comment by muggleorwizard** [comment]
Will this be applied to 1.20.1 as well as 1.21.1?

**Comment by mezz** [comment]
The code in Chipped changed a bit between versions, so I'll make a new PR for 1.20.1

**Comment by muggleorwizard** [comment]
> The code in Chipped changed a bit between versions, so I'll make a new PR for 1.20.1

Amazing, thanks mezz!
