### ISSUE TITLE
[Bug]: [1.21.1}

### ISSUE THREAD

**Issue by Periam** [CookieCNetwork/Chipped#351]
### Bug Description

After installing the mods, the game does not launch.
![Screenshot 2024-11-15 144413](https://github.com/user-attachments/assets/d67697d4-3e29-46e0-ad2f-dac5b275b75a)

### How to Reproduce?

1-Install Chipped
2-install Rechiseled: chipped
3-Install JEI
4-Launch the game

### Expected Behavior

To run after launching

### Version

chipped-neoforge-1.21.1-4.0.2

### Mod Loader Version

NeoForge 21.1.77

### Mod Loader

NeoForge

### Logs or additional context

https://pastebin.com/iPYtRZjS

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
This is an issue with rechiseled chiped not us

**Comment by Periam** [comment]
The second part where chipped is mentioned is not a bug?

**Comment by ThatGravyBoat** [comment]
that second part is because of rechiseled chipped crashing
