### ISSUE TITLE
"Mod chipped only supports ctm" crash

### ISSUE THREAD

**Issue by DrevianAlexander** [CookieCNetwork/Chipped#38]
![image](https://user-images.githubusercontent.com/9385253/119274584-d6b7ed80-bbcd-11eb-8ff1-7a1dc7a5c8fa.png)

Updated Chipped and this comes up. CTM is indeed installed

Crash Log paste: https://pastebin.com/r01pwJ6q

**Comment by Cinderheart** [comment]
Same. I'm just going to revert until it's fixed.

**Comment by terrariumearth** [comment]
looking at this pls use 1.0.5 for now

**Comment by JasonKillsUs** [comment]
same here...

**Comment by InfornoFire** [comment]
Fixed with https://github.com/CookieCNetwork/Chipped/commit/ac74335593bbce883e2caff0687ef4d5649500a4
