### ISSUE TITLE
Glass repetitive reversion recipe

### ISSUE THREAD

**Issue by InfornoFire** [CookieCNetwork/Chipped#44]
Needs looking into

**Comment by InfornoFire** [comment]
So its caused by this:
Each block belongs to the respective chipped tag to make recipe reversion simple. Aka stone would belong to chipped:stone tag which also has stone_1, stone_2, stone_3, etc
Glass belongs to all wood glass tags + its own tag, which means when it looks through the recipes it is seen 9 times (recipes pull from the tags)

**Comment by CodexAdrian** [comment]
Fixed in latest version
