### ISSUE TITLE
Connected Textures Don't Function

### ISSUE THREAD

**Issue by ghost** [CookieCNetwork/Chipped#51]
`Forge 36.1.16`
`CTM 1.1.2.6`
`Chipped 1.0.6.1`
[Mods List](https://gist.github.com/Brittank88/428a686a688818891916a3cabe6c3124)

No blocks from this mod have connected textures. Not sure why. Vanilla glass has connected textures though, for example.

**Comment by terrariumearth** [comment]
next update will be full addition of all CTM both fabric and forge
