### ISSUE TITLE
Crashing Happens every so often

### ISSUE THREAD

**Issue by zachsai** [CookieCNetwork/Chipped#56]
https://pastebin.com/amssLvTK

**Comment by zachsai** [comment]
Something to do with rendering of your blocks

**Comment by zachsai** [comment]
https://pastebin.com/Rpkd1FWz

Happened again while having no shaders on

**Comment by zachsai** [comment]
https://pastebin.com/Sszm7Lee

And another one again

**Comment by terrariumearth** [comment]
this seems to be at fault with the other mods you have installed. nothing it seems that we can fix :(
