### ISSUE TITLE
Machanist's Workbench: Slight Texture Issue

### ISSUE THREAD

**Issue by InterstellarSpaceCadet** [CookieCNetwork/Chipped#59]
I noticed there's a small issue with shadowing on the **mechanists's workbench**. 
The sides facing **north and south, in any light setting**, constantly have a **top down shadow**. I've rotated it and the issue is always on said sides.
![2021-06-29_12 40 35](https://user-images.githubusercontent.com/74081008/123844209-5b3a1200-d8d8-11eb-9267-cb59ea32530a.png)

**Comment by terrariumearth** [comment]
yeahh i knew about this, shouldn't effect game at all though it will be fixed in a future update!
