### ISSUE TITLE
Workbenches Not Usable & Missing textures for Fabric

### ISSUE THREAD

**Issue by MayhemWolf** [CookieCNetwork/Chipped#61]
All the torches are missing texture on Fabric 1.1 alongside the workbenches not being able to be used at all
![Torches](https://user-images.githubusercontent.com/86408066/124214734-8d4d9e80-daa7-11eb-9094-810d5b3734eb.PNG)

**Comment by terrariumearth** [comment]
@CodexAdrian @MsRandom

**Comment by MsRandom** [comment]
These issues have already been fixed before the latest commit.
Next release should have them fixed
