### ISSUE TITLE
Mods Missing alot of Forge Tags

### ISSUE THREAD

**Issue by ModernGamingWorld** [CookieCNetwork/Chipped#62]
#chipped:red_sandstone is missing from forge:sandstone/red

Chipped Terracotta is missing from #forge:terracotta

There might be much more, Id suggest checking for forge tags as I am sure I will find alot more

**Comment by InfornoFire** [comment]
There aren't many default ones to begin with, added in 1.2 but let me know if there are more
https://github.com/MinecraftForge/MinecraftForge/tree/1.15.x/src/generated/resources/data/forge/tags/blocks
