### ISSUE TITLE
Your recipetypes are registered under the minecraft namespace.

### ISSUE THREAD

**Issue by jaredlll08** [CookieCNetwork/Chipped#66]
The string passed into the `register` method is turned into a ResourceLocation, so all of [these](https://github.com/CookieCNetwork/Chipped/blob/1.16.5/src/main/java/com/grimbo/chipped/recipe/ChippedSerializer.java#L15-L21) get registered under the `minecraft` namespace instead of the `chipped` namespace.

**Comment by CodexAdrian** [comment]
Whoops. Thanks for pointing that out, fixed
