### ISSUE TITLE
[Request] Add data pack capabilities

### ISSUE THREAD

**Issue by faeldray** [CookieCNetwork/Chipped#67]
I'd love to be able to add more blocks to the work tables, like the different stone types from Create. But as far as I can tell, all of the block recipes are hard coded. So would it be possible to add more blocks via data packs or if it's already a thing, can you explain how I can do it? Thanks!

**Comment by CodexAdrian** [comment]
Our recipes are not hardcoded, but I will make a wiki page on how to add recipes with data packs, as our new recipe overhaul has made this process extremely easy.

**Comment by faeldray** [comment]
That would be perfect, thank you!

**Comment by CodexAdrian** [comment]
There is now a wiki page
