### ISSUE TITLE
Visual bug with connected textures

### ISSUE THREAD

**Issue by LeoBeliik** [CookieCNetwork/Chipped#70]
Forge 1.16.5 36.2.2
CTM 1.1.2.6
Chipped 1.1.2

Tested it with only chipped and ctm. 
Also, may i suggest somewhat of an indicator of what blocks have connected textures? so the player can know before crafting them.

![2021-08-17_16 41 20](https://user-images.githubusercontent.com/11804768/129790212-42e6012c-3e23-4c52-b4b2-537e7c03b70d.png)
![2021-08-17_16 41 25](https://user-images.githubusercontent.com/11804768/129790215-a177d921-60cf-463d-b804-075cbb32094f.png)

**Comment by Kekie6** [comment]
Thank you for notifying us about the issue, I will work on this soonish. However, this only concerns a few blocks and thus is not very urgent.
