### ISSUE TITLE
Fabric 1.17: Mason Workbench and Items produced from such unbreakable with tools

### ISSUE THREAD

**Issue by AzureMonument** [CookieCNetwork/Chipped#71]
Using Mc 1.17.1, Fabric 0.11.6, Fabric API 0.38.0, and chipped 1.1.1.

The mason table, and blocks produced by it (at least cobble) do not have an effective tool- using pickaxe is the same as any other tool, and the blocks fail to drop themselves on breaking.

**Comment by Jxsxxph** [comment]
That happens to me too. (1.17)

**Comment by MsRandom** [comment]
Fixed by #74
