### ISSUE TITLE
Weird workbench lighting with adjacent blocks

### ISSUE THREAD

**Issue by tlitookilakin** [CookieCNetwork/Chipped#78]
Placing solid/full blocks (ie. crafting table) to the right of a chipped workbench causes some (if experimental lighting is disabled) or all (if it's enabled) of the model faces on that side to turn completely black. Smooth lighting has no effect.

Forge 36.2.4
Chipped 1.1.2 forge
Minecraft 1.16.5

**Comment by Kekie6** [comment]
![afbeelding](https://user-images.githubusercontent.com/79649631/141953360-e8ec83c3-42f7-4340-87d6-20b855e3c3fa.png)
![afbeelding](https://user-images.githubusercontent.com/79649631/141953414-c0482fd9-96e3-4079-95df-461705604b26.png)
![afbeelding](https://user-images.githubusercontent.com/79649631/141953446-bf30cd23-0de5-4b9d-96f9-b85b9f1afada.png)

Added some images for visualization and verification of the bugs existence

**Comment by Synthestra** [comment]
Model issue

**Comment by InfornoFire** [comment]
> Seems to be fixed for all of the workbenches except the alchemy table

Eh that's fabric, idk what happens there. For forge the issue is more closely related to #23 which isn't done for any released versions of Chipped (alongside other things like 1 model per entire workbench)

**Comment by Synthestra** [comment]
> Eh that's fabric, idk what happens there.

I'm referring to forge, not fabric
