### ISSUE TITLE
Unoptimized workbench models

### ISSUE THREAD

**Issue by crosby-moe** [CookieCNetwork/Chipped#80]
While checking the workbench block models, I noticed 3 things that made them very unoptimized:
1. 0 width cubes still had 6 faces defined in the model file instead of only the 2 that are seen
2. Faces that are not visible normally (e.g. blocked by another cube) are still rendered
3. No culling at all (Note: do not use the auto cullface feature on blockbench, it breaks a lot of stuff so I'm doing it manually)

I'm already working on fixing them so don't worry about it, it should be complete in under a week

**Comment by Kekie6** [comment]
Hi, thank you for this advice! I am secretly a noob at modeling, so things like these are all new to me.
I will check out what exactly you mean, and i will apply these optimization features into future models where possible!

Thank you again :)

**Comment by crosby-moe** [comment]
I just got done working on optimizing the performance of the models
I'm _pretty_ sure there's no issues on it, but there may be one or two that slipped through the cracks
I kinda don't want to merge request on every branch, so I'll just leave it here in resource pack form [https://www.mediafire.com/file/uq1erfm6m5p7qrr/OptimizedModels.zip/file](https://www.mediafire.com/file/uq1erfm6m5p7qrr/OptimizedModels.zip/file)
If you compare the filesize of these with the old ones, you can already spot a pretty significant decrease

**Comment by Kekie6** [comment]
Hi, sorry for responding to you a bit late!

Thank you for optimizing these models. I will have a look at them and forward them to the coders for implementation.

Greetings,
Kekie
