### ISSUE TITLE
Incompatible with most Tech mods

### ISSUE THREAD

**Issue by Kasax007** [CookieCNetwork/Chipped#85]
Hey, I just figured out with assistance from the QuarryPlus mod creator that your mod is incompatible with most tech mods like Industrial Revolution or Applied Energistics. Whenever you have both mods combined it crashed the game upon loading the world. Only after removing chipped it is possible again. 
This might be an issue worth looking into since those tech mods are very popular. 
https://github.com/Kotori316/QuarryPlus/files/7497740/log.of.crash.txt <- Crashlog 

Best regards
Kasax007

**Comment by thecow275** [comment]
It seems to me that sodium is breaking rendering in some way that makes it incompatible with Chipped that much i can see from the log

**Comment by MsRandom** [comment]
This has been reported before, the issue is not related to tech mods, but with there being too many blocks with those mods together, we're still looking into finding a way to workaround that, until then, there's ways of increasing the limit, so you can use that.
