### ISSUE TITLE
Petición de configuración

### ISSUE THREAD

**Issue by DragonAstemirN** [CookieCNetwork/Chipped#91]
Realmente me encanta el diseño de las mesas de trabajo es increíble y demasiado bien hechos, en especial el telar es sorprendente, me gustaría poder tener únicamente habilitadas las mesas de trabajo sin añadir esa gran cantidad de bloques(contenido), si fuera posible tener esa opción en la configuración. 
De antemano gracias.

**Comment by Kekie6** [comment]
Hopefully one of you can speak spanish D:

**Comment by InfornoFire** [comment]
According to google translate: basically a config that can disable certain benches and all their blocks to reduce the # of blocks or something

**Comment by InfornoFire** [comment]
Stale, also I generally do not think this is a good idea anyways. Feel free to reopen if otherwise
