### ISSUE TITLE
[1.18.1 - Forge/Fabric] Suggestion: Mod Compatibility Consistency+

### ISSUE THREAD

**Issue by Quizer9O8** [CookieCNetwork/Chipped#92]
Consistency+ adds a lot of block variants of known blocks. Many of these can't be used directly into one of the 7 tables.
It would be nice if Consitency+ was present some of it's blocks could be used in tables as an alternative recipe.

**Comment by Kekie6** [comment]
very true indeed, I forgot all about this mod! its very nice, and by the looks of it, we barely overlap..,

**Comment by AlexNijjar** [comment]
We have no interest in adding mod compat for the foreseeable future.
