### ISSUE TITLE
Mason's table bug

### ISSUE THREAD

**Issue by LunafeyLazuli** [CookieCNetwork/Chipped#93]
(Submitting this bug for one of the members on my discord)
Version: chipped-1.18.1-1.2.0.1-forge.jar

Describe the bug/tweak
Issues with Chipped - Mason's table is not retrieved when breaking and has a long (obsidian-like) block break time
Chipped stone types do not have the "breakable with pickaxe" quality, and likewise do not drop bricks

Expected behavior
It should be easier to destroy these blocks and they should be dropped.

**Comment by InfornoFire** [comment]
Fixed in next version (applies to all blocks that require a tool)

**Comment by InfornoFire** [comment]
Fixed on 1.2.1
