### ISSUE TITLE
 Forge 1.18.1 Error loading mods with ctm

### ISSUE THREAD

**Issue by Edel-Lilies** [CookieCNetwork/Chipped#94]
Forge 39.0.9 Optifine H5 pre4 
Chipped 1.18.1-1.2.0.1  CTM-1.18-1.1.3+1
[latest.log](https://github.com/WillowWorks/Chipped/files/7798363/latest.log)
[crash-2022-01-02_08.49.42-fml.txt](https://github.com/WillowWorks/Chipped/files/7798364/crash-2022-01-02_08.49.42-fml.txt)
![QQ截图20220102084959](https://user-images.githubusercontent.com/73912246/147862562-9eb532e7-2b73-4db3-8643-2dc59e1e11ea.png)

**Comment by InfornoFire** [comment]
Fixed on 1.2.1 (please update)
